### ISSUE TITLE
2.6.1: migrations save first time gives error

### ISSUE THREAD

**Issue by srisub1** [prisma/migrate#579] opened 2020-09-03 13:30 UTC
## Bug description

I have a clean state with an empty db and a schema.prisma file. prisma migrate save gives me an error

## How to reproduce

1. prisma migrate save --name "dev" --experimental

It gives an error:
Error: Failure during a migration command: Connector error. (error: Error querying the database: No such table: Default._Migration
   0: migration_core::api::ListMigrations
             at migration-engine/core/src/api.rs:118)

## Expected behavior

In 2.5.x this used to work, so its new in 2.6.1

## Environment & setup

- OS: 
MacOS
- Database: 
PostreSQL
- Node.js version: 
v14.5.0
- Prisma version:

2.6.1

```

**Comment by pantharshit00** [comment] 2020-09-03 13:59
Hi,

Thanks for reporting this! It has already been reported before, so I am going to close this as a duplicate of https://github.com/prisma/migrate/issues/572

**Closed by pantharshit00** 2020-09-03 13:59 UTC
Labels: bug/0-needs-info, kind/bug
