### ISSUE TITLE
Error querying the database: foreign key mismatch

### ISSUE THREAD

**Issue by tkinte** [prisma/migrate#537] opened 2020-07-31 11:36 UTC
https://prisma-errors.netlify.app/report/9649

**Comment by tomhoule** [comment] 2020-12-17 10:27
This is caused by type mismatches in the referencing and referenced sides of a foreign key relation. This will be addressed by https://github.com/prisma/prisma/issues/4330

Thanks for reporting the crash!

**Closed by tomhoule** 2020-12-17 10:27 UTC
Labels: bug/1-repro-available, kind/bug, status/needs-action, team/migrations
