### ISSUE TITLE
Migration Error while using native 

### ISSUE THREAD

**Issue by wortforfilms** [prisma/migrate#662] opened 2020-12-04 17:09 UTC
Hi Prisma Team! Prisma Migrate just crashed. 

## Versions
      
| Name        | Version            |
|-------------|--------------------|
| Platform    | darwin             | 
| Node        | v15.3.0            | 
| Prisma CLI  | 2.10.2             | 
| Binary      | 7d0087eadc7265e12d4b8d8c3516b02c4c965111| 

## Error
```
Error: Error in migration engine: Dec 04 18:57:33.464  INFO migration_engine: Starting migration engine RPC server git_hash="7d0087eadc7265e12d4b8d8c3516b02c4c965111"
```

**Comment by Jolg42** [comment] 2020-12-11 09:40
Closing as duplicate of https://github.com/prisma/migrate/issues/661

**Closed by Jolg42** 2020-12-11 09:40 UTC
