### ISSUE TITLE
prisma2 migrate up => ERROR: querying the database: syntax error at or near ";"

### ISSUE THREAD

**Issue by FinnFrotscher** [prisma/migrate#365] opened 2020-03-11 11:10 UTC
`prisma2 migrate up --experimental` dies with
```
ERROR  Oops, an unexpected error occured!
Failure during a migration command: Connector error. (error: Error querying the database: Error querying the database: Error querying the database: db error: ERROR: syntax error at or near ";")
```

```
$ prisma2 version
prisma2@2.0.0-preview023, binary version: d3b0ceed5d87544b9d2decb70e08664f9047bb73
```

Output somewhat reduced:
```
DEBUG=* prisma2 migrate up --experimental --verbose                                                           prisma .env not loaded +0ms
  engineCommands getConfig, override prismaPath = undefined +0ms
  getos { platform: 'darwin', libssl: undefined } +0ms
  getos { platform: 'darwin', libssl: undefined } +43ms
 snapdragon:compiler initializing /Users/finnfrotscher/.nvm/versions/node/v12.14.1/lib/node_modules/prisma2/build/index.js +0ms


...


  snapdragon:parser initializing /Users/finnfrotscher/.nvm/versions/node/v12.14.1/lib/node_modules/prisma2/build/index.js +0ms
  getos { platform: 'darwin', libssl: undefined } +212ms
  LiftEngine:rpc starting migration engine with binary: /Users/finnfrotscher/.nvm/versions/node/v12.14.1/lib/node_modules/prisma2/migration-engine-darwin +0ms
  LiftEngine:rpc SENDING RPC CALL {} +3ms
  LiftEngine:stderr Mar 11 11:59:15.705  INFO migration_engine: Starting migration engine RPC server git_hash="d3b0ceed5d87544b9d2decb70e08664f9047bb73" +0ms
  LiftEngine:stderr Mar 11 11:59:15.821  INFO quaint::single: Starting a postgresql pool with 1 connections. +117ms
  LiftEngine:stderr Mar 11 11:59:16.159  INFO ListMigrations: migration_core::commands::list_migrations: Returning 4 migrations (0 pending). +337ms
🏋️‍  migrate up

Datamodel that will initialize the db:

generator photon {
  provider = "prisma-client-js"
  output   = "../@generated/prisma"
}

datasource db {
  provider = "postgresql"
  url = "***"
}

enum UserTypes {
  Admin
  Client
}

model User {
  id              String          @default(cuid())        @id
  type            UserTypes?      @default(Client)
}

model Project {
...
}
...

Checking the datasource for potential data loss...
  LiftEngine:rpc SENDING RPC CALL {"id":2,"jsonrpc":"2.0","method":"calculateDatabaseSteps","params":{"projectInfo":"","assumeToBeApplied":[],"stepsToApply":[{"tag":"CreateEnum","enum":"UserTypes","values":["Admin","Client"]},{"tag":"CreateEnum","enum":"RenderJobStatus","values":

...

{"tag":"CreateField","model":"RenderJob","field":"message","type":"String","arity":"Optional"},{"tag":"CreateField","model":"RenderJob","field":"error","type":"String","arity":"Optional"}],"sourceConfig":"generator photon {} +476ms
  LiftEngine:rpc SENDING RPC CALL {"id":3,"jsonrpc":"2.0","method":"calculateDatabaseSteps","params":{"projectInfo":"","assumeToBeApplied":[{"tag":"CreateEnum","enum":"UserTypes","values":["Admin","Client"]},{"tag":"CreateEnum","enum":"RenderJobStatus","values":["Waiting","InProgress","Done","Failed"]},{"tag":"CreateSource","source":"db"},{"tag":"CreateArgument","location":{"tag":"Source","source":"db"},"argument":"provider","value":"\"postgresql\""},{"tag":"CreateArgument","location":{"tag":"Source","source":"db"},"argument":"url","value":"env(\"POSTGRES_URL\")"},

...

{"tag":"CreateField","model":"Project","field":"template","type":"ProjectTemplates","arity":"Optional"},{"tag":"CreateDirective","location":{"path":{"tag":"Field","model":"Project","field":"template"},"directive":"default"}},{"tag":"CreateArgument","location":{"tag":"Directive","path":{"tag":"Field","model":"Project","field":"template"},"directive":"default"},"argument":"","value":"Manual"}],"sourceConfig":"generator photon {...} +1s


⚠️  There will be data loss:

  • You are about to alter the column `status` on the `RenderJob` table, which still contains 4 non-null values. The data in that column will be lost.
  • You are about to drop the column `header` on the `Shot` table, which still contains 425 non-null values.
  • You are about to alter the column `shotlist` on the `Shot` table, which still contains 436 non-null values. The data in that column will be lost.
  • You are about to alter the column `project` on the `Shotlist` table, which still contains 112 non-null values. The data in that column will be lost.
  • You are about to alter the column `email` on the `User` table, which still contains 4 non-null values. The data in that column will be lost.
  • You are about to alter the column `type` on the `User` table, which still contains 4 non-null values. The data in that column will be lost.
  • You are about to alter the column `status` on the `RenderJob` table, which still contains 4 non-null values. The data in that column will be lost.
  • You are about to drop the column `header` on the `Shot` table, which still contains 425 non-null values.
  • You are about to alter the column `shotlist` on the `Shot` table, which still contains 436 non-null values. The data in that column will be lost.
  • You are about to alter the column `project` on the `Shotlist` table, which still contains 112 non-null values. The data in that column will be lost.
  • You are about to alter the column `email` on the `User` table, which still contains 4 non-null values. The data in that column will be lost.
  • You are about to alter the column `type` on the `User` table, which still contains 4 non-null values. The data in that column will be lost.

✔ Are you sure you want to apply this change? … yes

Database Changes:

Migration       Database actionsStatus

20200311081858   statements.
20200311113400   statements.

You can get the detailed db changes with prisma2 migrate up --experimental --verbose
Or read about them in the ./migrations/MIGRATION_ID/README.md
  LiftEngine:rpc SENDING RPC CALL {"id":4,"jsonrpc":"2.0","method":"applyMigration","params":{"projectInfo":"","force":true,"migrationId":"20200311081858","steps":[{"tag":"CreateEnum","enum":"UserTypes","values":["Admin","Client"]},

...

{"tag":"CreateField","model":"RenderJob","field":"message","type":"String","arity":"Optional"},{"tag":"CreateField","model":"RenderJob","field":"error","type":"String","arity":"Optional"}],"sourceConfig":"generator photon {} +3s
  LiftEngine:rpc {
  LiftEngine:rpc   jsonrpc: '2.0',
  LiftEngine:rpc   error: {
  LiftEngine:rpc     code: 4466,
  LiftEngine:rpc     message: 'An error happened. Check the data field for details.',
  LiftEngine:rpc     data: {
  LiftEngine:rpc       is_panic: false,
  LiftEngine:rpc       message: 'Failure during a migration command: Connector error. (error: Error querying the database: Error querying the database: Error querying the database: db error: ERROR: syntax error at or near ";")',
  LiftEngine:rpc       backtrace: null
  LiftEngine:rpc     }
  LiftEngine:rpc   },
  LiftEngine:rpc   id: 4
  LiftEngine:rpc } +1s
 ERROR  Oops, an unexpected error occured!
Failure during a migration command: Connector error. (error: Error querying the database: Error querying the database: Error query
ing the database: db error: ERROR: syntax error at or near ";")
Please help us improve Prisma 2 by submitting an error report.
Error reports never contain personal or other sensitive information.
Learn more: https://pris.ly/d/telemetry

Failure during a migration command: Connector error. (error: Error querying the database: Error querying the database: Error query
ing the database: db error: ERROR: syntax error at or near ";")
Oops. We could not send the error report.

Thanks a lot for your help! 🙏
```

**Comment by martineboh** [comment] 2020-03-16 05:03
@FinnFrotscher I am currently having this same issue as you. From my Postgres log I can see this:
`syntax error at or near ";" at character 33`
`2020-03-16 04:02:34.307 UTC [265] STATEMENT:  ALTER TABLE "public"."Category" ;`
 Were you able to fix this?

**Comment by FinnFrotscher** [comment] 2020-03-16 07:22
no. i am updating the postgres instance manually right now. meaning every change in the prisma schema has to be translated to postgres by hand.

**Comment by janpio** [comment] 2020-03-16 17:13
Any concrete idea what is causing this? 
Could you maybe isolate the cause to build a reproduction?

**Comment by FinnFrotscher** [comment] 2020-03-17 17:21
Nope, no idea.

**Comment by FinnFrotscher** [comment] 2020-03-18 10:52
I would like to help you. i am currently working on the database. 
but i have no idea what is causing this or how to approach it.

**Comment by janpio** [comment] 2020-03-18 10:57
Are there already tables in the database?
Can you maybe share the current state of the DB and the schema you are trying to migrate to? (if not publicly, maybe in private?)

**Comment by FinnFrotscher** [comment] 2020-03-18 13:47
you want a dump of my db and the target schema i am trying to deploy?

**Comment by janpio** [comment] 2020-03-18 19:30
Schema only dump and new Prisma schema should be enough to reproduce the problem I think.

**Comment by FinnFrotscher** [comment] 2020-03-19 08:58
i have the schemadump and the schema.prisma ready. what address do i send them to?

**Comment by janpio** [comment] 2020-03-19 12:34
pant@prisma.io should be fine, make sure to include the link to this issue - then @pantharshit00 can try to create a reproduction.

**Comment by FinnFrotscher** [comment] 2020-03-24 09:11
@pantharshit00 @janpio any update?

**Comment by martineboh** [comment] 2020-03-24 15:52
This happens when I delete an already migrated model (table) from my schema.prisma file and never rerun the necessary commands to commit the change(deletion) to the Postgres DB, in this case the model below:
```
model Permission {
id     String @id  @default(cuid())
entity_id  String
user_id  String
createdAt   DateTime @default(now())
updatedAt  DateTime @updatedAt
}
```

After deleting the Permission model above, I added three other models below:

```
model EntityCanRead {
  permission_id          String @id @default(cuid())
  entity_id              String
  entity_type            String?
  user_id                String
  owner_id               String
  entity_group_id        String?
  createdAt              DateTime @default(now())
  updatedAt              DateTime @updatedAt
}

model EntityCanWrite {
  permission_id          String @id @default(cuid())
  entity_id              String
  entity_type            String?
  user_id                String
  owner_id               String
  entity_group_id        String?
  createdAt              DateTime @default(now())
  updatedAt              DateTime @updatedAt
}

model EntityCanDelete {
  permission_id          String @id @default(cuid())
  entity_id              String
  entity_type            String?
  user_id                String
  owner_id               String
  entity_group_id        String?
  createdAt              DateTime @default(now())
  updatedAt              DateTime @updatedAt
}

```
...before running the necessary commands: `prisma2 migrate save --experimental`, `prisma2 migrate up --experimental` and `prisma2 generate` and I got this message:

```
ERROR  Oops, an unexpected error occured!
Failure during a migration command: Connector error. (error: Error querying the database: Error querying the database: Error querying the database: db error: ERROR: syntax error at or near ";")

```

**Temporary fix though**: Creating another Postgres DB, deleting the migration folder and re-runing the commands: `prisma2 migrate save --experimental`, `prisma2 migrate up --experimental` and `prisma2 generate` seems to fix the issue everytime.

Windows 10. 
prisma2@2.0.0-preview024, binary version: 377df4fe30aa992f13f1ba152cf83d5770bdbc85

**Comment by tvvignesh** [comment] 2020-04-02 14:37
Even I faced this issue today (when I already had data in the db) - finally figured out that I had a column in the DB and the migration was trying to create the same column again (not sure why) leading to this error. I deleted the column and the migration worked. 

![Screenshot from 2020-04-02 19-39-45](https://user-images.githubusercontent.com/1165845/78262003-96a33080-751d-11ea-9c4b-44ce3c883aa3.png)

**Comment by tylerjbainbridge** [comment] 2020-04-10 20:03
I encountered this when _attempting_ to migrate from preview24 to the beta- I think it's caused by these empty ALTER TABLE SQL statements.

```sql
ALTER TABLE "public"."Collection" ;

ALTER TABLE "public"."CollectionBlock" ;

ALTER TABLE "public"."CollectionEntry" ;

ALTER TABLE "public"."File" ;

ALTER TABLE "public"."GoogleAccount" ;

When run (from the README.md) in the migration folder- it yields the same error: 
![image](https://user-images.githubusercontent.com/13852400/79019626-cb7a3d80-7b44-11ea-8078-67a1941f0d28.png)

```

**Comment by ajaymore** [comment] 2020-04-13 09:10
> I encountered this when _attempting_ to migrate from preview24 to the beta- I think it's caused by these empty ALTER TABLE SQL statements.
> 
> ```sql
> ALTER TABLE "public"."Collection" ;
> 
> ALTER TABLE "public"."CollectionBlock" ;
> 
> ALTER TABLE "public"."CollectionEntry" ;
> 
> ALTER TABLE "public"."File" ;
> 
> ALTER TABLE "public"."GoogleAccount" ;
> ```
> 
> When run (from the README.md) in the migration folder- it yields the same error:
> ![image](https://user-images.githubusercontent.com/13852400/79019626-cb7a3d80-7b44-11ea-8078-67a1941f0d28.png)
> 
> ```
> ERROR:  syntax error at or near ";"
> LINE 1: ALTER TABLE "public"."Collection" ;
>                                           ^
> ```
I found the same issue. migrate is unable to execute below empty statements and hence failing. Is there any workaround available? Can I delete these statements and run the migration?

```sql
ALTER TABLE "my_db"."AssignTo" ;

ALTER TABLE "my_db"."Category" ;

ALTER TABLE "my_db"."License" ;

ALTER TABLE "my_db"."Location" ;

ALTER TABLE "my_db"."MicroLearningSchedule" ;

ALTER TABLE "my_db"."MicroLearningSessionAnswer" ;

ALTER TABLE "my_db"."Quiz" ;

ALTER TABLE "my_db"."QuizAnswer" ;

ALTER TABLE "my_db"."SafetyObservation" ;

ALTER TABLE "my_db"."User" ;
```

**Comment by tylerjbainbridge** [comment] 2020-04-14 13:34
@ajaymore Did you find any workarounds for this? This is blocking me from upgrading to the beta and I don't want to be stranded at preview24 😫.

**Comment by tomhoule** [comment] 2020-04-14 14:53
If my understanding of the problem is right, this should already be fixed on the latest alpha - https://github.com/prisma/prisma-engines/pull/670 has a more general solution, it will be merged soon and should land on alpha today.

**Comment by tylerjbainbridge** [comment] 2020-04-14 14:54
That's great news! Thanks for the heads up.

**Comment by pantharshit00** [comment] 2020-04-15 18:34
@tylerjbainbridge Since the PR is now merged can you please try the alpha version and see if this is fixed for you: `npm install @prisma/cli@alpha`.

**Comment by tylerjbainbridge** [comment] 2020-04-15 20:31
Yes! This solved it for me. Thanks!

**Comment by pantharshit00** [comment] 2020-04-21 12:03
@FinnFrotscher Are you still facing this with the latest version?

**Comment by joneslloyd** [comment] 2020-05-11 10:06
Using `@prisma/cli@alpha` does not solve it for me (this is in my devDependencies: `"@prisma/cli": "^2.0.0-alpha.1199",`).

I get this error on migrate:
```
Checking the datasource for potential data loss...

Database Changes:

Migration                                      Database actions      Status

20200511105503-added-bool-fields-for-no-dates  3 RawSql statements.  

You can get the detailed db changes with prisma migrate up --experimental --verbose
Or read about them in the ./migrations/MIGRATION_ID/README.md
 ERROR  Oops, an unexpected error occured!
Failure during a migration command: Connector error. (error: Error querying the database: 
Error querying the database: near ",": syntax error
   0: migration_core::api::ApplyMigration
           with migration_id="20200511105503-added-bool-fields-for-no-dates"
             at migration-engine/core/src/api.rs:77)
Please help us improve Prisma 2 by submitting an error report.
Error reports never contain personal or other sensitive information.
Learn more: https://pris.ly/d/telemetry
```

It only succeeds if I delete the DB and run this from scratch (no DB).

**Comment by pantharshit00** [comment] 2020-05-20 07:54
Hey @joneslloyd 

Can you please open a new issue with a sql dump of your database schema. Then we an try to reproduce the error and fix it. Thanks!

**Comment by joneslloyd** [comment] 2020-05-20 09:00
@pantharshit00 I'm not sure if it'd be of use now, because it's changed a lot since my original post, and I "overcame" the issue by dropping all tables and re-running.

Also, rookie question: How would I dump the schema if you still think this would be of use to you? It's a sqlite DB accessed via TablePlus.

**Comment by pantharshit00** [comment] 2020-06-05 06:17
Hi @joneslloyd 


You can upload the sqlite file here or mail it to "schemas@prisma.io" if the information is private.

Also, if you can't reproduce the error anymore then no need of that. Otherwise, also outline the steps to reproduce this.

**Comment by tomhoule** [comment] 2020-08-24 10:54
I think this was fixed a while ago in the migration engine. Can someone still reproduce this problem on the latest release?

**Comment by albertoperdomo** [comment] 2020-10-22 09:52
Should be fixed now. Closing.

**Closed by albertoperdomo** 2020-10-22 09:52 UTC
Labels: bug/0-needs-info, kind/bug, team/support
