### ISSUE TITLE
Using `env("DATABASE_URL")` freezes migrations

### ISSUE THREAD

**Issue by peterp** [prisma/migrate#433] opened 2020-04-29 08:28 UTC
Whilst running `yarn prisma migrate up --experimental`

if the var is named `DATABASE_URL` then we see this (when running netlify build locally):
```
Checking the datasource for potential data loss...
Error: Failure during a migration command: The migration produced an invalid schema.
Datamodel error in schema that could not be rendered. Error validating source `DS`: The URL for datasource `DS` must start with the protocol `sqlite://`.
```

if we change the variable to any other name then we get:
```
Checking the datasource for potential data loss...
Database Changes:
Migration                   Database actions           Status
20200427153228-create-user  1 CreateTable statements.  Done 🚀  
You can get the detailed db changes with prisma migrate up --experimental --verb
ose
Or read about them in the ./migrations/MIGRATION_ID/README.md
🚀    Done with 1 migration in 4.63s.
Migrate database up... [completed]
Done in 7.35s.
```

datasource looks like:
```
datasource DS {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}```

**Comment by pantharshit00** [comment] 2020-04-30 09:51
Thanks all, I can reproduce this problem. I think this is related to how we are parsing `steps.json`. I think in development you have generated a migration which we are trying to apply as if it was sqlite database even though we have changed the provider.

Exact steps for reproduction:
1. Clone https://github.com/thedavidprice/netlify-2-deploy-test
2. Run 
```
yarn install
export BINARY_TARGET="[\"native\"]"
# point to your own instance
export DATABASE_URL=postgresql://pg:pg@localhost:5432/issue_redwood?schema=public
```
3. Goto `api/prisma/schema.prisma` and change provider to `postgresql` and url to `url = env("DATABASE_URL")`
4. Run `yarn workspace api prisma migrate up --experimental`


@tomhoule will look into this now as he is currently working on the migration engine.

**Comment by mavilein** [comment] 2020-04-30 10:44
As of now this is not really a bug imo as it is unintended to switch providers like this. The steps.json contains this:
```json
{
      "tag": "CreateArgument",
      "location": {
        "tag": "Source",
        "source": "DS"
      },
      "argument": "provider",
      "value": "\"sqlite\""
}
```
Hence the provider is locked to sqlite for this migration. We recently introduced validation of datasource URLs hence you are seeing the error complaining about the protocol. 

The problem will be fixed through this [feature](https://github.com/prisma/prisma/issues/1487) for dynamic providers.

**Comment by cannikin** [comment] 2020-04-30 16:56
I have so many questions...

* Was datasource URL validation only added in beta3? We've had no issues before this
* Why would everything work via `netlify build`, as long as we change the ENV var name?
* How come it can connect to the database, see that the migration hasn't run, actually create the `_Migration` table, and *then* fail?
* Is the protocol supposed to be `postgres://` or `postgresql://`? When we grab the connection string from a Heroku PG instance it gives us `postgres://` and that has worked in the past.

We developed a workaround for dynamic provider names so Redwood users could dev in sqlite and deploy in postgres but it seems like this release has rendered our workaround obsolete. If I'm interpreting this correctly, a user absolutely cannot dev in one database provider and deploy in another until https://github.com/prisma/prisma/issues/1487 is complete?

**Comment by cannikin** [comment] 2020-04-30 21:29
We think we came up with another hack on top of our previous hack. 😅A couple of weeks ago we created [netlify-plugin-prisma-provider]() to replace the provider name in `schema.prisma` at build time. I just pushed up a new version that also replaces it in the migrations' snapshots of `schema.prisma`. I was able to deploy successfully! Note that this wouldn't help running migrations locally, this is only for going from a dev environment to Netlify, and when your repo contains "sqlite" as the provider.

I've noticed that the provider is also declared in the `steps.json` that's generated in each migration directory, and it contains a JSON-ified version of the declaration from `schema.prisma`:

```json
{
  "tag": "CreateArgument",
  "location": {
    "tag": "Source",
    "source": "DS"
  },
  "argument": "provider",
  "value": "\"sqlite\""
},
```

Do I need to replace it there as well? 😬

**Comment by cannikin** [comment] 2020-05-01 21:21
Okay we invented a workaround. It looks like when the provider in `steps.json` doesn’t match the provider in `schema.prisma` there’s another check on the env var name which happens to be DATABASE_URL (also saved in `steps.json`) and even though that var exists, it blows up because the providers don’t match. So now our [Netlify deploy plugin](https://github.com/redwoodjs/netlify-plugin-prisma-provider) swaps out “sqlite” for "postgresql" or "mysql" everywhere—main `schema.prisma`, migrations’ copies of `schema.prisma`, and in all copies of `steps.json`.

No matter what you try to do to stop us, we will prevail in letting that provider name be dynamic! 😂 Just kidding, love you guys!

**Comment by thedavidprice** [comment] 2020-05-01 23:53
If it's of interest, here's my comment about how we resolved this in our [related Redwood Issue](https://github.com/redwoodjs/redwood/issues/469#issuecomment-622608642).

Regarding the [dynamic provider](https://github.com/prisma/prisma/issues/1487), based on what we've learned here, it does not seem the current validation logic will work with a dynamic provider. **One idea for a way forward** --> provide a cli option for applying a migration to effectively "--force" the migration despite a mismatch in either `url` or `provider` values.

I 100% understand the validation checks Prisma needs to perform between values in `steps.json` and `schema.prisma`. However, one thought and one suggestion here:

**Release Notes (fwiw)** 
We are attempting to be _very_ meticulous when reading release notes for each new version of Prisma. Something definitely changed in the validation logic between beta.2 and beta.3, which we didn't see when reading about the release. (It's likely in there and we just missed or didn't understand it.) Just know the time you take to make those notes is not taken for granted and detail + depth is greatly appreciated (within reason of course).

**Migration Validation Logic (suggestion)** 
Something definitely doesn't make sense about the current validation logic involving datasource `url` and `provider` values. If the `url` values are a match, but `provider` values do not match, the migration process fails. _However,_ if the `url` values do **not** match, the migration will proceed regardless of the `provider` values. This behavior was definitely unexpected, and it's not clear if it's accidental or intentional. Lastly, although I understand the intention behind including the `url` ENV var value in the matching, I'm not quite sure it's necessary -- the string value of the ENV var is what really matters, and if that's incorrect, the whole thing fails anyway.

Thanks again!

**Comment by mavilein** [comment] 2020-07-20 13:48
Datasource providers with multiple providers are implemented now. So this should work now.

**Closed by mavilein** 2020-07-20 13:48 UTC
Labels: bug/2-confirmed, kind/bug, team/engines, team/product, topic: ecosystem

**Comment by softmarshmallow** [comment] 2020-11-24 02:17
I'm getting this on fresh-new project. dugh..

**Comment by softmarshmallow** [comment] 2020-11-24 03:49
I removed "" on DATABASE_URL

DATABASE_URL="~~" to DATABASE_URL=~~
