### ISSUE TITLE
Error: Error in migration engine. Reason: [/rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7/src/libcore/str/mod.rs:1920:47] byte index 1 is out of bounds of `` 

### ISSUE THREAD

**Issue by divyenduz** [prisma/migrate#510] opened 2020-07-10 12:57 UTC
Command: `prisma migrate save --experimental`
Version: `2.2.0`
Binary Version: `45c4da4dd3ccd6a322796b228bdf937c7ce884e8`
Report: https://prisma-errors.netlify.app/report/8640 
OS: `x64 darwin 19.5.0`

JS Stacktrace:
```
Error: Error in migration engine.
Reason: [/rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7/src/libcore/str/mod.rs:1920:47] byte index 1 is out of bounds of ``

Please create an issue in the migrate repo with
your `schema.prisma` and the prisma command you tried to use 🙏:
https://github.com/prisma/migrate/issues/new

    at ChildProcess.child.on (/Users/kaisky89/.nvm/versions/node/v10.21.0/lib/node_modules/@prisma/cli/build/index.js:2:2370192)
    at ChildProcess.emit (events.js:198:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
```

Rust Stacktrace:
```
[/rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7/src/libcore/str/mod.rs:1920:47] byte index 1 is out of bounds of ``
```

**Comment by tomhoule** [comment] 2020-07-13 14:16
@divyenduz  did you manage to reproduce that last week? I gave it a quick try, and I can't reproduce the crash.

**Comment by pantharshit00** [comment] 2020-08-05 21:44
I was also unable to reproduce this. We have missing migrations in the data collected:
<img width="468" alt="image" src="https://user-images.githubusercontent.com/22195362/89467259-dd868880-d792-11ea-9d97-a785b8378d15.png">

So this is hard to reproduce imo. We also can't trace back the report to anyone so we are blind here.

**Comment by divyenduz** [comment] 2020-08-05 23:06
Did you both try it with this specific version of MariaDB? 
https://github.com/prisma/prisma/issues/3095#issuecomment-665596987

**Comment by tomhoule** [comment] 2020-08-06 06:25
Nope, I tried it with whatever version I had installed. There is a lot going on this cycle for me, so I will try to find the time to try to reproduce this on the right version of MariaDB, but it's unlikely I will get to it very soon.

**Comment by divyenduz** [comment] 2020-08-06 06:35
This is easily reproducible with this specific version of MariaDB.

**Comment by janpio** [comment] 2020-08-06 12:15
> This is easily reproducible with this specific version of MariaDB.

This information should be added to the original issue and issue title then.

**Comment by divyenduz** [comment] 2020-08-06 12:59
> This information should be added to the original issue and issue title then.

Someone else besides me needs to confirm that. Once that is done, we can change the title

**Comment by pantharshit00** [comment] 2020-08-07 11:54
I am unable to reproduce this with this docker image:
```yaml
# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mariadb:10.1.36
    restart: always
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
```

![image](https://user-images.githubusercontent.com/22195362/89643127-be8f1000-d8d2-11ea-8c65-eb48220ebe2f.png)

Schema taken from the error report.

**Comment by do4gr** [comment] 2020-11-10 16:21
We recently implemented a fix for default value parsing on MySQL variants. Since then we cannot reproduce this anymore. I am closing this therefore.

**Closed by do4gr** 2020-11-10 16:21 UTC
Labels: bug/1-repro-available, kind/bug, status/needs-action
