### ISSUE TITLE
Error on migrate up a migration

### ISSUE THREAD

**Issue by gabrielbusarello** [prisma/migrate#277] opened 2019-12-30 01:42 UTC
Hi everyone,

Can be a mistake from me, but I having some problems with the migrations.

Error appears when I make some changes with n:m relation.

Here is the error: https://gist.github.com/gabrielbusarello/efc2c41bbd3f11b0970162ee3695a7ab

I have leaving some things pass or really exists a problem?

Thank you!

**Comment by gabrielbusarello** [comment] 2020-01-13 14:17
Hi, sorry for await too long.

So, that is my repository: https://github.com/gabrielbusarello/bt-api

To do what's causing this issue, you have to change some field or data types from some n:m relation.

When you run the `prisma2 lift save` runs fine. So appears some warnings, of constraints and register losts. Until that, all is fine.

When you run `prisma2 lift up`, then the warning of constraints becomes an error, becouse, I think of prisma cannot drop all the tables and create again, because of the constraints.

Sorry by my english. But I'm learning yet.

**Comment by pantharshit00** [comment] 2020-01-27 14:20
Can you please try this again with the latest version of prisma2 and report back? It might be already fixed.

**Comment by gabrielbusarello** [comment] 2020-02-01 19:39
I've ran `npm i -g prisma2` and `prisma2 lift save`, but that has been renamed to migrate, so I ran 'prisma2 migrate save --experimental', and get that error:
<img width="1116" alt="Captura de Tela 2020-02-01 às 16 37 17" src="https://user-images.githubusercontent.com/25415068/73597999-5faaa180-4511-11ea-971f-ca070fff367b.png">

**Comment by pantharshit00** [comment] 2020-02-03 12:11
Hm, the error suggests that the binary wasn't downloaded.

Can you run the following command and paste the output here? These commands run prisma2 in debug mode.
```
export DEBUG=*
npm install -g prisma2
prisma2 migrate save --experimental
```

**Comment by gabrielbusarello** [comment] 2020-02-09 12:22
Hi,

There is the error:
<img width="1116" alt="Captura de Tela 2020-02-09 às 09 21 38" src="https://user-images.githubusercontent.com/25415068/74101945-a6a22380-4b1d-11ea-979d-c0dcd4176558.png">

Sorry for waiting.

**Comment by pantharshit00** [comment] 2020-02-11 12:38
Hm, did the cli properly downloaded the binary when you ran `npm install -g prisma2`? I am not able to reproduce on my machine

**Comment by gabrielbusarello** [comment] 2020-02-17 11:12
Yes... But in my machine I was installing with `sudo` the `prisma2` package, you think this have to do with?

**Comment by pantharshit00** [comment] 2020-02-26 13:25
> Yes... But in my machine I was installing with sudo the prisma2 package, you think this have to do with?

That might be a possibility. Try fixing the permission of the folder using https://docs.npmjs.com/resolving-eacces-permissions-errors-when-installing-packages-globally

**Closed** 2020-05-26 08:07 UTC
Labels: bug/0-needs-info, kind/bug
