### ISSUE TITLE
Feature request: In-Database migration lock

### ISSUE THREAD

**Issue by nickreynke** [prisma/migrate#425] opened 2020-04-19 17:56 UTC
## Problem

Consider deploying a Node.js server twice (because of horizontal scaling; maybe load balancing), and both of them would call a `prisma migrate up` while deploying. What could happen now is that Node.js server 1 tries to migrate while Node.js server 2 also tries the same. This could maybe result in conflicts within the database.

## Solution

A "In-Database" migration lock on a table designed specifically for locking.

Workflow would be as follows:

* First `prisma migrate up` tries to create special table and maybe sets a boolean value indicating that a migration is running
* Any other script now running `prisma migrate up` sees the lock in the table and skips the migration
* When the initial `prisma migrate up` finishes, the lock within the database "unlocks"

**Comment by nickreynke** [comment] 2020-12-02 04:36
@albertoperdomo Have you guys put a thought on this? :) Or is there a "best practice" to this kind of issue?

**Comment by tomhoule** [comment] 2020-12-02 06:29
It is something we have plans for, it will come as soon as there is time to work on it: https://github.com/prisma/prisma-engines/issues/1118

**Comment by tomhoule** [comment] 2020-12-17 10:15
Let's close this issue as a duplicate of https://github.com/prisma/prisma-engines/issues/1118

Work on this is planned.

**Closed by tomhoule** 2020-12-17 10:15 UTC
Labels: datamodel-migrations, kind/feature, team/migrations
