### ISSUE TITLE
Unexpected migration failure when making column unique if there are exising non-unique values

### ISSUE THREAD

**Issue by abuuzayr** [prisma/migrate#442] opened 2020-05-10 23:50 UTC
## Bug description

Migration fails unexpectedly with error message `Oops, an unexpected error occured!` when converting an existing field in schema to unique by adding `@unique` if there are existing duplicate values in the table column. 

## How to reproduce

1. Create schema with a non-unique field
2. Populate field in table with non-unique values
3. Update the schema and make the (previously non-unique) field unique
4. Run migration
5. See error

## Expected behavior

The error message should be clearer on what the problem is. Similar to the data loss messages when there is potential data loss on migration, we can have:

```bash
⚠️  There will be data loss:

  • Adding unique constraint to column `column`. There are duplicated keys in this column, it is not possible.
```

## Prisma information

Sent report id: **5083**

```
# Migration `20200510173030-make-job-aggid-unique`

This migration has been generated by Abu Uzayr at 5/10/2020, 5:30:30 PM.
You can check out the [state of the schema](./schema.prisma) after the migration.

## Database Steps

```sql
CREATE UNIQUE INDEX "Job.aggId" ON "public"."Job"("aggId")
```
```
## Changes

```diff
diff --git schema.prisma schema.prisma
migration 20200510171048-make-company-name-unique..20200510173030-make-job-aggid-unique
--- datamodel.dml
+++ datamodel.dml
@@ -2,9 +2,9 @@
 // learn more about it in the docs: https://pris.ly/d/prisma-schema
 datasource postgresql {
   provider = "postgresql"
-  url = "***"
+  url      = env("DATABASE_URL")
 }
 generator client {
   provider = "prisma-client-js"
@@ -14,9 +14,9 @@
 // --------------------------------------
 model Job {
   id          Int      @default(autoincrement()) @id
-  aggId       String?
+  aggId       String?  @unique
   name        String
   company     Company  @relation(fields: [companyId], references: [id])
   companyId   Int
   avatar      String?
```

## Environment & setup

- OS: Mac OS
- Database: PostgreSQL
- Prisma version: 1.34.10
- Node.js version: v12.13.0

**Comment by pantharshit00** [comment] 2020-06-05 06:13
Hi @abuuzayr 

Sorry for the late reply here.

I am unable to reproduce this problem in the latest version:
![image](https://user-images.githubusercontent.com/22195362/83842981-b293a000-a721-11ea-9775-f49c62455b5d.png)


Version I used for reproduction:
```
Environment variables loaded from ./prisma/.env
@prisma/cli          : 2.0.0-alpha.1299
Current platform     : debian-openssl-1.1.x
Query Engine         : query-engine d88852ac341cdf3c7379a08fa1ebc5c444a4aa67 (at /home/harshit/code/reproductions/issue-migrate_442/node_modules/@prisma/cli/query-engine-debian-openssl-1.1.x)
Migration Engine     : migration-engine-cli d88852ac341cdf3c7379a08fa1ebc5c444a4aa67 (at /home/harshit/code/reproductions/issue-migrate_442/node_modules/@prisma/cli/migration-engine-debian-openssl-1.1.x)
Introspection Engine : introspection-core d88852ac341cdf3c7379a08fa1ebc5c444a4aa67 (at /home/harshit/code/reproductions/issue-migrate_442/node_modules/@prisma/cli/introspection-engine-debian-openssl-1.1.x)
Format Binary        : prisma-fmt d88852ac341cdf3c7379a08fa1ebc5c444a4aa67 (at /home/harshit/code/reproductions/issue-migrate_442/node_modules/@prisma/cli/prisma-fmt-debian-openssl-1.1.x)
```

Can you please try again with the latest version?

**Comment by albertoperdomo** [comment] 2020-07-08 09:20
Please link to existing issue @Jolg42

**Comment by Jolg42** [comment] 2020-07-08 09:22
https://github.com/prisma/migrate/issues/471

**Comment by tomhoule** [comment] 2020-11-05 10:38
We do have a warning/validation for this now, closing the issue.

**Closed by tomhoule** 2020-11-05 10:38 UTC
Labels: kind/improvement
