### ISSUE TITLE
Getting error on lift save

### ISSUE THREAD

**Issue by malekjaroslav** [prisma/migrate#238] opened 2019-12-09 10:22 UTC
Getting this error every time I change something in schema, create migration, then update something else in the schema and try to create a new migration. The only way I found to fix it is to erase all migrations and start from scratch...

Running on `preview-018`

```
Response: {
  "jsonrpc": "2.0",
  "error": {
    "code": 4466,
    "message": "The migration engine panicked while handling the request. Check the data field for details.",
    "data": {
      "message": "Failure during a migration command: Generic error. (error: The field isTemporary on model User already exists in this Datamodel. It is not possible to create it once more.)",
      "backtrace": null
    }
  },
  "id": 2
}
```

**Comment by malekjaroslav** [comment] 2019-12-09 18:55
I upgraded from 17.2, but this happened even after I deleted the previous migrations and created a first one. Then it started to complain about the field I added in the previous migration (the new one, also on preview 18).

**Comment by malekjaroslav** [comment] 2019-12-09 18:58
The way to reproduce it would be to 
1) create a datamodel, 
2) create a migration with lift save
3) Add a new field
4) Create a migration again
---
5) If it did not crash maybe just try to make the added field optional with `?` and try to create a new migration

**Comment by malekjaroslav** [comment] 2019-12-10 05:00
This https://github.com/prisma/lift/issues/236 could be a related issue

**Comment by pantharshit00** [comment] 2019-12-11 18:40
Can you try this on alpha once? We did some lift fixes today so this might be fixed with it as I was unable to reproduce it on alpha
```
npm install -g prisma2@alpha
```

**Closed** 2020-03-13 03:46 UTC
Labels: bug/0-needs-info, kind/bug
