### ISSUE TITLE
Running `prisma migrate save --experimental` hangs

### ISSUE THREAD

**Issue by jayanth1991** [prisma/migrate#399] opened 2020-04-02 00:36 UTC
## Bug description
When there is no database created on MySQL5.7 and you run the command, it gives the option to "Create new MySQL database ..." and when you select the option. It doesn't throw any error, doesn't terminate. However, the database does get created on the server.

## How to reproduce
1) Use this schema
```prisma
datasource db {
  provider = "mysql"
  url      = env("DATABASE_URL")
}

generator client {
  provider = "prisma-client-js"
}

model Post {
  id        Int     @id @default(autoincrement())
  title     String
  content   String?
  published Boolean @default(false)
  author    User?   @relation(fields: [authorId], references: [id])
  authorId  Int?
}

model User {
  id    Int     @id @default(autoincrement())
  email String  @unique
  name  String?
  posts Post[]
}
```

1) run `prisma migrate save --experimental` -- this never terminates
2) Logon to the MySQL server and run `show databases;` it should show a new database

## Expected behavior
The program doesn't throw any error not does it terminate.

## Environment & setup

- OS: Windows 10
- Database: MySQL5.7
- Prisma version: 2.0.0-beta1

**Comment by pantharshit00** [comment] 2020-04-21 12:11
Hi,

Thanks for reporting this! It has already been reported before, so I am going to close this as a duplicate of https://github.com/prisma/migrate/issues/342

**Closed by pantharshit00** 2020-04-21 12:11 UTC
