### ISSUE TITLE
`prisma2 migrate save` prompt on a new sqlite database is missing the first letter of the database

### ISSUE THREAD

**Issue by Errorname** [prisma/migrate#349] opened 2020-02-14 10:19 UTC
Schema.prisma:
```prisma
datasource db {
  provider = "sqlite"
  url      = "file:dev.db"
}
...
```

Then running `prisma2 migrate save --experimental` will prompt:
```
You are trying to create a migration for Sqlite database ev.db.
A database with that name doesn't exist at file:dev.db.
Do you want to create the database?

┌─ Database options ────────────────────────────────────┐
│                                                                                                                                                                                        │
│ ❯ Yes            Create new Sqlite database ev.db                                                                                                                                      │
│   No             Don't create the database                                                                                                                                             │
│                                                                                                                                                                                        │
└───────────────────────────────────────────────────────┘


```

It prints "ev.db" instead of "dev.db", but the command will still creates the database with the correct name

**Comment by pantharshit00** [comment] 2020-02-14 13:34
Hi,

Thanks for reporting this! It has already been reported before, so I am going to close this as a duplicate of https://github.com/prisma/migrate/issues/283

**Closed by pantharshit00** 2020-02-14 13:34 UTC
