### ISSUE TITLE
"Connector error. (error: Error querying the database: Error querying the database: Error querying the database: Server error: ERROR 42S02 (1146): Table '_issue_client_502._migration' doesn't exist')" + "DROP TABLE `_issue_client_502`.`_migration`;" in migration README

### ISSUE THREAD

**Issue by janpio** [prisma/migrate#373] opened 2020-03-18 23:57 UTC
1. Clone https://github.com/harshit-test-org/prisma2-client-502
2. `yarn`
3. Adapt `prisma/.env` to point to local MySQL 5.7 installation
4. `yarn prisma2 migrate save --experimental`
4. `yarn prisma2 migrate up --experimental`
5. See:
	```
	You can get the detailed db changes with prisma2 migrate up --experimental --verbose
	Or read about them in the ./migrations/MIGRATION_ID/README.md
	 ERROR  Oops, an unexpected error occured!
	Failure during a migration command: Connector error. (error: Error querying the database: Error querying the database: Error querying the database: Server error: `ERROR 42S02 (1146): Table '_issue_client_502._migration' doesn't exist')
	Please help us improve Prisma 2 by submitting an error report.
	Error reports never contain personal or other sensitive information.
	Learn more: https://pris.ly/d/telemetry
5. open `prisma\migrations\20200319005000-init\README.md` and see:
	```sql
	...
	ALTER TABLE `_issue_client_502`.`UserOrganization` ADD FOREIGN KEY (`user`) REFERENCES `_issue_client_502`.`User`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE
	
	DROP TABLE `_issue_client_502`.`_migration`;
	```

(preview022 + preview024)

**Comment by webnoob** [comment] 2020-03-26 16:29
I've been running into a similar issue as this.

I run `npx prisma2 migrate up --experimental` and it complains the __migrations table doesn't exist. I then run it a second time and it complains my tables already exist and from that point on my db is complete and has the __migrations table and all the other tables from my model.

**Comment by pantharshit00** [comment] 2020-04-22 10:23
@janpio I am unable to reproduce this now. 

I adjusted the datamodel to match the new spec, here it is now: 
```prisma
model Organization {
  id        Int       @default(autoincrement()) @id
  uid       String?   @unique
  name      String
  createdAt DateTime  @default(now())
  updatedAt DateTime  @updatedAt
  deletedAt DateTime?
}

model UserOrganization {
  organization   Organization @relation(fields: [organizationId], references: [id])
  organizationId Int
  role           Role         @relation(fields: [roleId], references: [id])
  roleId         Int
  user           User         @relation(fields: [userId], references: [id])
  userId         Int
  createdAt      DateTime     @default(now())
  updatedAt      DateTime     @updatedAt

  @@id([roleId, userId, organizationId])
}

model User {
  id        Int                @default(autoincrement()) @id
  uid       String?            @unique
  email     String             @unique
  firstName String?
  lastName  String?
  createdAt DateTime           @default(now())
  updatedAt DateTime           @updatedAt
  deletedAt DateTime?
  orgs      UserOrganization[]
}

model Role {
  id          Int                @default(autoincrement()) @id
  uid         String?            @unique
  name        String
  description String?
  createdAt   DateTime           @default(now())
  updatedAt   DateTime           @updatedAt
  orgs        UserOrganization[]
}
```

**Comment by webnoob** [comment] 2020-04-22 10:33
I still get this on whenever I do a migration on the latest version with MySQL 8.0.

I can't really share my schema but it's nothing special and the schema you've posted should be pretty similar in terms of relations etc.

**Comment by pantharshit00** [comment] 2020-04-24 10:22
@webnoob Without a reproduction, unfortunately, we can't help here.

**Comment by webnoob** [comment] 2020-04-24 10:23
I'll try and make a minimal repro.

**Comment by webnoob** [comment] 2020-04-24 10:43
@pantharshit00 Can I share my schema in private somehow?

**Comment by pantharshit00** [comment] 2020-04-24 11:55
Yep, `schemas@prisma.io` works for that :)

**Comment by webnoob** [comment] 2020-04-24 11:59
You've got mail ;)

**Comment by pantharshit00** [comment] 2020-04-29 13:57
@webnood I am still unable to reproduce this. 

You might need to drop the `_Migrations` table and try again.

**Comment by webnoob** [comment] 2020-04-29 14:14
@pantharshit00 
This happens on a clean DB with no tables in it at all. Does that help? Perhaps that's the issue?

I'm in early stage development of my app so when I make DB changes, I just drop all tables and then run the lift save, lift up so just answer your suggestion, this always happens when I've dropped the migrations table.

**Comment by pantharshit00** [comment] 2020-04-29 14:25
I am using the latest version, so please do try the latest version:
![image](https://user-images.githubusercontent.com/22195362/80607497-312a5d00-8a53-11ea-86ca-e1ac128c08ae.png)

Maybe send your `migrations` folder as well to `schemas@prisma.io` if you can still reproduce. Also, try resetting everything by deleting that folder and trying again

**Comment by webnoob** [comment] 2020-04-29 14:34
Ok will do - just to clarify, I always start from scratch. Drop the tables and delete the migrations folder creating it again with `lift save`.

I won't be able to test this properly on beta.3 until next week as I'm going through some refactoring. 

I'll come back ASAP. Shall I email migrations to the same schema@prisma.io email address?

**Comment by pantharshit00** [comment] 2020-04-29 14:42
> Ok will do - just to clarify, I always start from scratch. Drop the tables and delete the migrations folder creating it again with lift save.
`lift save` was rename to `migrate save` a few releases back.

> I'll come back ASAP. Shall I email migrations to the same schemas@prisma.io email address?
Yep, same email

**Comment by webnoob** [comment] 2020-04-29 14:53
> lift save was rename to migrate save a few releases back.
Sorry, stuck on the same terminology. I call the correct call, don't worry :)

I call `npx prisma migrate save --experimental`

then

`npx prisma migrate up --experimental`

**Comment by webnoob** [comment] 2020-04-29 22:15
@pantharshit00 

Ok, still getting the error. I'm going to be as verbose as possible and will also send an email with my shema, migrations and verbose output.

Windows 10.
MySQL 8.0
DB name: dev
Using beta.3 for both @prisma/client and @prisma/cli

1. Starting with clean DB - no tables, functions, stored procedures etc.
2. Starting with **only** `schema.prisma` file in my `/prisma` directory.
3. Run `SET DATABASE_URL=mysql://user:password@localhost:3306/dev&& prisma migrate save --experimental`
4. Migration Name: `Init`. **Note**: Output of this is contained in the emailed file `ConsoleOutputFromMigrateSave.txt`
5. At this point, if I refresh the DB tables, I now have a `_migration` table which is empty.
6. Run `SET DATABASE_URL=mysql://user:password@localhost:3306/dev&& prisma migrate up --experimental --verbose`
7. ERROR. **Note:** Output of this is contained in the emailed file `ConsoleOutPutFromMigrateSave.txt`

Excerpt:
```
Database Changes:

Migration            Database actions                         Status

20200429225740-init  1 DropTable, 12 CreateTable statements.

You can get the detailed db changes with prisma migrate up --experimental --verbose
Or read about them in the ./migrations/MIGRATION_ID/README.md
 ERROR  Oops, an unexpected error occured!
Please help us improve Prisma 2 by submitting an error report.
Error reports never contain personal or other sensitive information.
```
8. If I refresh the DB tables list now, the `_migration` table is gone but the other tables have been created.
9. Run the `migrate up` command again
10.  Error (more or less the same as the other, but with this as the output at the end:
```
Database Changes:

Migration            Database actions                          Status

20200429225740-init  12 DropTable, 11 CreateTable statements.

You can get the detailed db changes with prisma migrate up --experimental --verbose
Or read about them in the ./migrations/MIGRATION_ID/README.md
 ERROR  Oops, an unexpected error occured!
Please help us improve Prisma 2 by submitting an error report.
Error reports never contain personal or other sensitive information.
```

Now if I refresh my tables, they are all present and I have a failed migration in the `_migration` table with the errors of:

```
["ConnectorError { user_facing_error: None, kind: QueryError(Error querying the database: Server error: `ERROR 42S01 (1050): Table 'book' already exists') }"]
```

These are the exact steps I am taking (I've run them each in turn as I've been writing the email) so can't provide any more information than this. If you can't recreate it, perhaps make sure you're doing the same thing with env vars etc!? 

If you really can't recreate it, I'd be happy to do a screen share over zoom / something else to show you the issue this end. Not sure what the policy is at this point :)

**Comment by webnoob** [comment] 2020-05-13 08:34
Any update on this one?

**Comment by grunghi** [comment] 2020-05-13 09:36
I'm having similiar issues with fresh MySQL database on Windows.

My environment:
Windows 10
MariaDB 10.1.38
@prisma/cli 2.0.0-beta.5

When I run `npx prisma migrate up --experimental` for the first time it crashes like this:

```
Database Changes:

Migration            Database actions                        Status

20200512194047-init  1 DropTable, 6 CreateTable statements.

You can get the detailed db changes with prisma migrate up --experimental --verbose
Or read about them in the ./migrations/MIGRATION_ID/README.md
Failure during a migration command: Connector error.
(error: Error querying the database: Error querying the database: 
Server error: `ERROR 42S02 (1146): Table 'prisma-migrate-test._migration' doesn't exist'
   0: migration_core::api::ApplyMigration
           with migration_id="20200512194047-init"
```
(Report id 5312)

When I run it for the second time it crashes like this:

```
Database Changes:

Migration            Database actions                        Status

20200512194047-init  7 DropTable, 6 CreateTable statements.

You can get the detailed db changes with prisma migrate up --experimental --verbose
Or read about them in the ./migrations/MIGRATION_ID/README.md
Failure during a migration command: Connector error. 
(error: Error querying the database: Error querying the database:
 Server error: `ERROR 42S01 (1050): Table 'user' already exists'
   0: migration_core::api::ApplyMigration
           with migration_id="20200512194047-init"
```
(Report id 5313)

**Comment by grunghi** [comment] 2020-05-25 21:53
I've just tried this on a different Windows 10 machine with fresh MySQL 8.0.20 install and the migrate command fails in the same fashion.

Migrations work fine when using the PostgreSQL connector.

**Comment by xlxAciDxlx** [comment] 2020-05-26 02:36
Referencing [this issue](https://github.com/prisma/migrate/issues/339#issue-558260407) because it's relevant. It still occurs to this day, even on a fresh install of Prisma, fresh schema, etc.

**Comment by 0xCAP** [comment] 2020-05-26 15:29
Just installed tried Prisma for the first time. Issue #339 just happened to me too.

**Comment by webnoob** [comment] 2020-06-01 09:39
It'd be really nice to at least get a bug confirmed tag on this one to see some progress. It's been over 2 months and there seems to be plenty of recreation info.

**Comment by pantharshit00** [comment] 2020-06-01 11:52
@webnoob Yeah, sorry we are focusing on Prisma client right now so there is a delay. This issue is windows specific. Related to how MySQL's innodb engine handles casing on windows.

I am going to close this as a duplicate of https://github.com/prisma/migrate/issues/339

**Closed by pantharshit00** 2020-06-01 11:52 UTC
Labels: bug/0-needs-info, kind/bug

**Comment by govmusik** [comment] 2020-09-05 18:46
This still happen, any fix? I send the migrations folder to schemas@prisma.io

**Comment by Karl-EdwardFPJeanMehu** [comment] 2020-09-20 02:23
Any updates?

**Comment by markjackson02** [comment] 2020-11-06 17:38
I thought I might be able to get around this issue by running `blitz db migrate` within Windows Subsystem for Linux (WSL) but I still get the same error.

```
Error: P1014

The underlying table for model `_migration` does not exist.
```

Will be keeping an eye on https://github.com/prisma/prisma-engines/issues/950 for the fix, thanks

**Comment by tomhoule** [comment] 2020-11-06 18:06
@markjackson02 migrate can run inside or outside the WSL — the difference is where the MySQL server is run. If it is run within the WSL, it will be case sensitive and migrate will work.

**Comment by jerots** [comment] 2020-11-08 11:40
I just had this issue on my Mac - MySQL RDS. turns out the db user i was using didn't have enough permission. I gave it full permission to the schema and it fixed my _Migration issue
