### ISSUE TITLE
User does not have root privilege 

### ISSUE THREAD

**Issue by alexthegoodman** [prisma/migrate#99] opened 2019-08-09 16:15 UTC
As you can see, there is an error when I try to create the first migration. This happens regardless if the Database already exists, and whether or not I use PostgreSQL or MySQL.

```
Alexs-MacBook-Pro-2:ts-react-graphql-starter-kit alex$ prisma2 -v
prisma2@2.0.0-preview-6, binary version: 4d17a0639165e5a8e54c7e5cf538ffdf114edb53

Alexs-MacBook-Pro-2:ts-react-graphql-starter-kit alex$ DATABASE_URL=mysql://root:root@localhost:3306/reeviewr-prisma prisma2 lift save --name 'init'

Error: Error in lift engine for rpc listMigrations:
  thread 'main' panicked at 'The user does not have root privelege and can not create a new database: QueryError(Error { kind: Io, cause: Some(Os { code: 54, kind: ConnectionReset, message: "Connection reset by peer" }) }
```

```
datasource db {
  provider = "mysql"
  url      = "mysql://root:root@localhost:3306/reeviewr-prisma"
}
```

**Comment by pantharshit00** [comment] 2019-08-14 10:54
I am unable to reproduce this. I think this is more related to the permission of the User that you are using.

<img width="1080" alt="Screenshot 2019-08-14 at 4 15 50 PM" src="https://user-images.githubusercontent.com/22195362/63015593-fd041180-beae-11e9-83fb-85c92826c022.png">


Also, please tell the MySQL version you are using. I am using the following version locally:

![image](https://user-images.githubusercontent.com/22195362/63015372-60417400-beae-11e9-9b8b-2b5e0ec30b07.png)

Also, try running `ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY 'password'` if you are on MySQL 8

**Comment by alexthegoodman** [comment] 2019-08-14 22:51
I'm using MySQL 5.7.25, but all is well now with Postgres.

**Comment by artemzakharov** [comment] 2019-08-15 01:35
Interesting, I was able to fix it by switching to MySQL 😅 Just going to start with a fresh database and call it a day, although I've noticed the error does still pop up when trying to specify the schema with Postres, and that may be looking into in the future.

**Comment by janpio** [comment] 2019-09-02 14:42
Anyone still having this problem or can we close this then?

**Closed** 2020-04-27 18:50 UTC
Labels: bug/0-needs-info, kind/bug
