### ISSUE TITLE
Migration fails after changing ENUM

### ISSUE THREAD

**Issue by malekjaroslav** [prisma/migrate#358] opened 2020-02-25 10:15 UTC
After updating to preview 22 and migrating the DB, everything worked fine. But then when I changed one enum it started failing.
Migrations now contain `TestStatus_new` which I guess is used to migrate the enum from `TestStatus`. But it contains it even though I deleted all tables from the DB and migrations too

```
 ERROR  Oops, an unexpected error occured!
Failure during a migration command: Connector error. (error: Error queryin
g the database: Error querying the database: Error querying the database: 
db error: ERROR: type "TestStatus_new" already exists)
``` 

**UPDATE**: Deleting the whole DB helps

**Comment by pantharshit00** [comment] 2020-02-26 12:03
I can confirm this bug. I would guess that we are somehow using the old migrate logic even after updating the enum implementation to use native database types.

Steps to reproduce:
1. Bootstrap the following datamodel:
	```prisma
	datasource db {
	  provider = "postgresql"
	  url      = env("DATABASE_URL")
	}
	
	generator client {
	  provider = "prisma-client-js"
	}
	
	enum Permissions {
	  ADMIN
	  USER 
	}
	
	model User {
	  id String @id @default(cuid())
	  name String
	  permission Permissions[]
	}
	```
2. Add some data to the application via studio: `prisma2 studio --experimental`. Make sure at least one row uses the `USER` enum
2. Change it to the following datamodel and perform a migration:
	```prisma
	datasource db {
	  provider = "postgresql"
	  url      = env("DATABASE_URL")
	}
	
	generator client {
	  provider = "prisma-client-js"
	}
	
	enum Permissions {
	  ADMIN
	  ASSOCIATE 
	}
	
	model User {
	  id String @id @default(cuid())
	  name String
	  permission Permissions[]
	}
   ```

It should throw the following Rust panic:
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/22195362/75343257-0f2f2580-58be-11ea-8d85-4793ee6fbc6a.png">


Version: `prisma2@2.0.0-alpha.832, binary version: 687716d3305368e3f586f8957de2037fd8a50f8f`

**Comment by kaedub** [comment] 2020-06-24 18:23
Is there a workaround for this?

**Comment by shixian-hf** [comment] 2020-07-10 18:35
Can someone suggests some fix for this problem? instead of deleting the whole DB...  (but yeah delete the whole DB works for me)

**Comment by malekjaroslav** [comment] 2020-07-11 02:34
@shixian-hf run `DROP SCHEMA public CASCADE`

**Comment by albertoperdomo** [comment] 2020-08-05 09:41
Duplicate of #414

**Closed** 2020-08-14 06:53 UTC
Labels: bug/2-confirmed, engines/migration engine, kind/bug, team/engines
