### ISSUE TITLE
New database but "All migrations are already applied"

### ISSUE THREAD

**Issue by nickreynke** [prisma/migrate#50] opened 2019-07-14 09:23 UTC
I did the [Prisma2 tutorial](https://github.com/prisma/prisma2/blob/master/docs/tutorial.md), created the first model `User`, let me generate migration files via `prisma2 lift save --name 'init'` and ran `prisma2 lift up`. It worked but didn't check if the database then actually changed. (Am using Postgres via a Docker Compose.)

I then completely stopped the Postgres server and removed its associated volume that was created via my Docker Compose file:

```docker-compose
version: "3"

services:

  postgres:
    image: postgres:11-alpine
    restart: always
    ports:
      - "5433:5432"
    volumes:
      - postgres:/var/lib/postgresql
    environment:
      POSTGRES_PASSWORD: "prisma"
      POSTGRES_USER: "prisma"
      POSTGRES_DB: "prisma"

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  postgres:
```

So the data was completely gone. I then re-upped the Docker services and ran `prisma2 lift up` to migrate my Postgres database to the last state.

The output was `All migrations are already applied` but there are no tables, since I've completely renewed the Postgres server.

Is this intentionally?

**Comment by pantharshit00** [comment] 2019-07-18 17:10
Can you please check whether there is a `_Migrations` table?

I am unable to reproduce this. Please double-check via the UI.

**Comment by nickreynke** [comment] 2019-07-23 14:21
@pantharshit00 may have looked into the wrong schema. It's working. The default schema was `default@default`, or something like that. Forcibly set it to `prisma` with an environment variable. Filled with data :)

**Comment by ryands17** [comment] 2019-12-11 19:33
@pantharshit00 this issue still persists with the SQLite DB.
prisma2 version: `2.0.0-preview018.1`
OS: Linux

**Comment by BjoernRave** [comment] 2019-12-12 18:04
I have the same issue with a postgreSQL database

**Comment by tomhoule** [comment] 2019-12-13 13:16
I can confirm this should be fixed in preview018.2

**Closed** 2020-05-20 09:55 UTC
Labels: bug/2-confirmed, kind/bug
