### ISSUE TITLE
Postgres: @default(uuid()) maps to text instead of uuid

### ISSUE THREAD

**Issue by steebchen** [prisma/migrate#499] opened 2020-07-03 16:11 UTC
A uuid type string currently maps to `text`, but instead should map to postgres' native `uuid` type.

more internal context: https://prisma-company.slack.com/archives/C1FPU5FPT/p1593790745201800

**Comment by pantharshit00** [comment] 2020-07-05 10:48
Closing this as a duplicate of https://github.com/prisma/migrate/issues/114

**Closed by pantharshit00** 2020-07-05 10:48 UTC
Labels: team/product, topic: types
