### ISSUE TITLE
Cockroachdb Support in Migrate

### ISSUE THREAD

**Issue by fire** [prisma/migrate#268] opened 2019-12-26 17:58 UTC
Tracking interest and progress of Cockroachdb integration with migrate.

https://www.cockroachlabs.com/

**Comment by fire** [comment] 2019-12-26 18:08
Appears to hang on connect.

**Comment by pantharshit00** [comment] 2019-12-27 16:18
Can you please run lift in debug mode and paste the output here?

To enable debug mode, run `export DEBUG=*` before running your lift command.

**Comment by pantharshit00** [comment] 2019-12-27 16:21
Also, we haven't tested lift with cockroachdb at all so rough edges are expected here. Under the hood, we use the rust driver for postgres: https://github.com/sfackler/rust-postgres#tokio-postgres-

**Comment by fire** [comment] 2020-01-07 06:13
Sorry, I ran out of bandwidth to work on this.

**Comment by janpio** [comment] 2020-05-20 09:47
Duplicate of https://github.com/prisma/migrate/issues/426

**Comment by albertoperdomo** [comment] 2020-05-20 09:48
Global issue to track support for CockroachDB is [here](https://github.com/prisma/prisma/issues/2523).

**Closed by janpio** 2020-05-20 09:47 UTC
Labels: kind/feature, team/engines
