### ISSUE TITLE
[Bug] Error on a migration rollback.

### ISSUE THREAD

**Issue by sameoldmadness** [prisma/migrate#201] opened 2019-10-28 20:00 UTC
Given a SQLite database
When I remove a field from the schema

```
 model Workflow {
   id           String   @default(cuid()) @idan 
-  description  String?
```

And create the migration and run it

```PRAGMA foreign_keys=OFF;
CREATE TABLE "lift"."new_Workflow" (
  "id" TEXT NOT NULL   ,
  PRIMARY KEY ("id")
);
INSERT INTO "new_Workflow" ("id") SELECT "id" from "Workflow"
DROP TABLE "lift"."Workflow";
ALTER TABLE "lift"."new_Workflow" RENAME TO "Workflow";
PRAGMA "lift".foreign_key_check;
PRAGMA foreign_keys=ON;
```

And run `migrate down` command
I see an error

```
Rolling back migration 20191028152012-remove-field
Error: QueryError(QueryError(QueryError(SqliteFailure(Error { code: Unknown, extended_code: 1 }, Some("object name reserved for internal use: sqlite_autoindex_Batch_1"))

stack backtrace:
   0: backtrace::backtrace::trace
   1: backtrace::capture::Backtrace::new_unresolved
   2: failure::backtrace::internal::InternalBacktrace::new
   3: <failure::backtrace::Backtrace as core::default::Default>::default
   4: prisma_query::connector::sqlite::error::<impl core::convert::From<rusqlite::error::Error> for prisma_query::error::Error>::from
   5: prisma_query::connector::metrics::query
   6: <prisma_query::connector::sqlite::Sqlite as prisma_query::connector::queryable::Queryable>::query_raw
   7: <sql_migration_connector::migration_database::Sqlite as sql_migration_connector::migration_database::MigrationDatabase>::query_raw
   8: sql_migration_connector::sql_database_step_applier::SqlDatabaseStepApplier::apply_next_step
   9: <sql_migration_connector::sql_database_step_applier::SqlDatabaseStepApplier as migration_connector::database_migration_step_applier::DatabaseMigrationStepApplier<sql_migration_connector::sql_migration::SqlMigration>>::unapply_step
  10: <migration_connector::migration_applier::MigrationApplierImpl<T> as migration_connector::migration_applier::MigrationApplier<T>>::unapply
  11: <migration_engine::commands::unapply_migration::UnapplyMigrationCommand as migration_engine::commands::command::MigrationCommand>::execute
  12: <migration_engine::api::MigrationApi<C,D> as migration_engine::api::GenericApi>::unapply_migration
  13: migration_engine::api::rpc::RpcApi::create_sync_handler
  14: tokio_executor::enter::exit
  15: tokio_threadpool::blocking::blocking
  16: <futures::future::lazy::Lazy<F,R> as futures::future::Future>::poll
  17: futures::future::chain::Chain<A,B,C>::poll
  18: <futures::future::then::Then<A,B,F> as futures::future::Future>::poll
  19: <futures::future::lazy::Lazy<F,R> as futures::future::Future>::poll
  20: <futures::future::then::Then<A,B,F> as futures::future::Future>::poll
  21: <futures::future::map::Map<A,F> as futures::future::Future>::poll
  22: <futures::future::either::Either<A,B> as futures::future::Future>::poll
  23: <futures::future::map::Map<A,F> as futures::future::Future>::poll
  24: <futures::future::map_err::MapErr<A,F> as futures::future::Future>::poll
  25: <futures::stream::and_then::AndThen<S,F,U> as futures::stream::Stream>::poll
  26: <futures::stream::forward::Forward<T,U> as futures::future::Future>::poll
  27: <futures::future::map::Map<A,F> as futures::future::Future>::poll
  28: <futures::future::map_err::MapErr<A,F> as futures::future::Future>::poll
  29: futures::task_impl::std::set
  30: std::panicking::try::do_call
  31: __rust_maybe_catch_panic
  32: tokio_threadpool::task::Task::run
  33: tokio_threadpool::worker::Worker::run_task
  34: tokio_threadpool::worker::Worker::run
  35: std::thread::local::LocalKey<T>::with
  36: std::thread::local::LocalKey<T>::with
  37: std::thread::local::LocalKey<T>::with
  38: tokio::runtime::threadpool::builder::Builder::build::{{closure}}
  39: std::thread::local::LocalKey<T>::with
  40: std::thread::local::LocalKey<T>::with
  41: std::sys_common::backtrace::__rust_begin_short_backtrace
  42: std::panicking::try::do_call
  43: __rust_maybe_catch_panic
  44: core::ops::function::FnOnce::call_once{{vtable.shim}}
  45: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
  46: std::sys::unix::thread::Thread::new::thread_start
  47: _pthread_body
  48: _pthread_start
)

stack backtrace:
   0: backtrace::backtrace::trace
   1: backtrace::capture::Backtrace::new_unresolved
   2: failure::backtrace::internal::InternalBacktrace::new
   3: <failure::backtrace::Backtrace as core::default::Default>::default
   4: <failure::error::error_impl::ErrorImpl as core::convert::From<F>>::from
   5: sql_migration_connector::sql_database_step_applier::SqlDatabaseStepApplier::apply_next_step
   6: <sql_migration_connector::sql_database_step_applier::SqlDatabaseStepApplier as migration_connector::database_migration_step_applier::DatabaseMigrationStepApplier<sql_migration_connector::sql_migration::SqlMigration>>::unapply_step
   7: <migration_connector::migration_applier::MigrationApplierImpl<T> as migration_connector::migration_applier::MigrationApplier<T>>::unapply
   8: <migration_engine::commands::unapply_migration::UnapplyMigrationCommand as migration_engine::commands::command::MigrationCommand>::execute
   9: <migration_engine::api::MigrationApi<C,D> as migration_engine::api::GenericApi>::unapply_migration
  10: migration_engine::api::rpc::RpcApi::create_sync_handler
  11: tokio_executor::enter::exit
  12: tokio_threadpool::blocking::blocking
  13: <futures::future::lazy::Lazy<F,R> as futures::future::Future>::poll
  14: futures::future::chain::Chain<A,B,C>::poll
  15: <futures::future::then::Then<A,B,F> as futures::future::Future>::poll
  16: <futures::future::lazy::Lazy<F,R> as futures::future::Future>::poll
  17: <futures::future::then::Then<A,B,F> as futures::future::Future>::poll
  18: <futures::future::map::Map<A,F> as futures::future::Future>::poll
  19: <futures::future::either::Either<A,B> as futures::future::Future>::poll
  20: <futures::future::map::Map<A,F> as futures::future::Future>::poll
  21: <futures::future::map_err::MapErr<A,F> as futures::future::Future>::poll
  22: <futures::stream::and_then::AndThen<S,F,U> as futures::stream::Stream>::poll
  23: <futures::stream::forward::Forward<T,U> as futures::future::Future>::poll
  24: <futures::future::map::Map<A,F> as futures::future::Future>::poll
  25: <futures::future::map_err::MapErr<A,F> as futures::future::Future>::poll
  26: futures::task_impl::std::set
  27: std::panicking::try::do_call
  28: __rust_maybe_catch_panic
  29: tokio_threadpool::task::Task::run
  30: tokio_threadpool::worker::Worker::run_task
  31: tokio_threadpool::worker::Worker::run
  32: std::thread::local::LocalKey<T>::with
  33: std::thread::local::LocalKey<T>::with
  34: std::thread::local::LocalKey<T>::with
  35: tokio::runtime::threadpool::builder::Builder::build::{{closure}}
  36: std::thread::local::LocalKey<T>::with
  37: std::thread::local::LocalKey<T>::with
  38: std::sys_common::backtrace::__rust_begin_short_backtrace
  39: std::panicking::try::do_call
  40: __rust_maybe_catch_panic
  41: core::ops::function::FnOnce::call_once{{vtable.shim}}
  42: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
  43: std::sys::unix::thread::Thread::new::thread_start
  44: _pthread_body
  45: _pthread_start
)

stack backtrace:
   0: backtrace::backtrace::trace
   1: backtrace::capture::Backtrace::new_unresolved
   2: failure::backtrace::internal::InternalBacktrace::new
   3: <failure::backtrace::Backtrace as core::default::Default>::default
   4: <failure::error::error_impl::ErrorImpl as core::convert::From<F>>::from
   5: <sql_migration_connector::sql_database_step_applier::SqlDatabaseStepApplier as migration_connector::database_migration_step_applier::DatabaseMigrationStepApplier<sql_migration_connector::sql_migration::SqlMigration>>::unapply_step
   6: <migration_connector::migration_applier::MigrationApplierImpl<T> as migration_connector::migration_applier::MigrationApplier<T>>::unapply
   7: <migration_engine::commands::unapply_migration::UnapplyMigrationCommand as migration_engine::commands::command::MigrationCommand>::execute
   8: <migration_engine::api::MigrationApi<C,D> as migration_engine::api::GenericApi>::unapply_migration
   9: migration_engine::api::rpc::RpcApi::create_sync_handler
  10: tokio_executor::enter::exit
  11: tokio_threadpool::blocking::blocking
  12: <futures::future::lazy::Lazy<F,R> as futures::future::Future>::poll
  13: futures::future::chain::Chain<A,B,C>::poll
  14: <futures::future::then::Then<A,B,F> as futures::future::Future>::poll
  15: <futures::future::lazy::Lazy<F,R> as futures::future::Future>::poll
  16: <futures::future::then::Then<A,B,F> as futures::future::Future>::poll
  17: <futures::future::map::Map<A,F> as futures::future::Future>::poll
  18: <futures::future::either::Either<A,B> as futures::future::Future>::poll
  19: <futures::future::map::Map<A,F> as futures::future::Future>::poll
  20: <futures::future::map_err::MapErr<A,F> as futures::future::Future>::poll
  21: <futures::stream::and_then::AndThen<S,F,U> as futures::stream::Stream>::poll
  22: <futures::stream::forward::Forward<T,U> as futures::future::Future>::poll
  23: <futures::future::map::Map<A,F> as futures::future::Future>::poll
  24: <futures::future::map_err::MapErr<A,F> as futures::future::Future>::poll
  25: futures::task_impl::std::set
  26: std::panicking::try::do_call
  27: __rust_maybe_catch_panic
  28: tokio_threadpool::task::Task::run
  29: tokio_threadpool::worker::Worker::run_task
  30: tokio_threadpool::worker::Worker::run
  31: std::thread::local::LocalKey<T>::with
  32: std::thread::local::LocalKey<T>::with
  33: std::thread::local::LocalKey<T>::with
  34: tokio::runtime::threadpool::builder::Builder::build::{{closure}}
  35: std::thread::local::LocalKey<T>::with
  36: std::thread::local::LocalKey<T>::with
  37: std::sys_common::backtrace::__rust_begin_short_backtrace
  38: std::panicking::try::do_call
  39: __rust_maybe_catch_panic
  40: core::ops::function::FnOnce::call_once{{vtable.shim}}
  41: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
  42: std::sys::unix::thread::Thread::new::thread_start
  43: _pthread_body
  44: _pthread_start
)
```

**Comment by pantharshit00** [comment] 2019-10-29 11:00
I can confirm this bug.

full stack trace:
```
Rolling back migration 20191029115652-remove-content
Error: QueryError(QueryError(QueryError(SqliteFailure(Error { code: Unknown, extended_code: 1 }, Some("object name reserved for internal use: sqlite_autoindex_User_1"))

stack backtrace:
   0: backtrace::backtrace::trace
   1: backtrace::capture::Backtrace::new_unresolved
   2: failure::backtrace::internal::InternalBacktrace::new
   3: <failure::backtrace::Backtrace as core::default::Default>::default
   4: prisma_query::connector::sqlite::error::<impl core::convert::From<rusqlite::error::Error> for prisma_query::error::Error>::from
   5: prisma_query::connector::metrics::query
   6: <prisma_query::connector::sqlite::Sqlite as prisma_query::connector::queryable::Queryable>::query_raw
   7: <sql_migration_connector::migration_database::Sqlite as sql_migration_connector::migration_database::MigrationDatabase>::query_raw
   8: sql_migration_connector::sql_database_step_applier::SqlDatabaseStepApplier::apply_next_step
   9: <sql_migration_connector::sql_database_step_applier::SqlDatabaseStepApplier as migration_connector::database_migration_step_applier::DatabaseMigrationStepApplier<sql_migration_connector::sql_migration::SqlMigration>>::unapply_step
  10: <migration_connector::migration_applier::MigrationApplierImpl<T> as migration_connector::migration_applier::MigrationApplier<T>>::unapply
  11: <migration_engine::commands::unapply_migration::UnapplyMigrationCommand as migration_engine::commands::command::MigrationCommand>::execute
  12: <migration_engine::api::MigrationApi<C,D> as migration_engine::api::GenericApi>::unapply_migration
  13: migration_engine::api::rpc::RpcApi::create_sync_handler
  14: tokio_executor::enter::exit
  15: tokio_threadpool::blocking::blocking
  16: <futures::future::lazy::Lazy<F,R> as futures::future::Future>::poll
  17: futures::future::chain::Chain<A,B,C>::poll
  18: <futures::future::then::Then<A,B,F> as futures::future::Future>::poll
  19: <futures::future::lazy::Lazy<F,R> as futures::future::Future>::poll
  20: <futures::future::then::Then<A,B,F> as futures::future::Future>::poll
  21: <futures::future::map::Map<A,F> as futures::future::Future>::poll
  22: <futures::future::either::Either<A,B> as futures::future::Future>::poll
  23: <futures::future::map::Map<A,F> as futures::future::Future>::poll
  24: <futures::future::map_err::MapErr<A,F> as futures::future::Future>::poll
  25: <futures::stream::and_then::AndThen<S,F,U> as futures::stream::Stream>::poll
  26: <futures::stream::forward::Forward<T,U> as futures::future::Future>::poll
  27: <futures::future::map::Map<A,F> as futures::future::Future>::poll
  28: <futures::future::map_err::MapErr<A,F> as futures::future::Future>::poll
  29: futures::task_impl::std::set
  30: std::panicking::try::do_call
  31: __rust_maybe_catch_panic
  32: tokio_threadpool::task::Task::run
  33: tokio_threadpool::worker::Worker::run_task
  34: tokio_threadpool::worker::Worker::run
  35: std::thread::local::LocalKey<T>::with
  36: std::thread::local::LocalKey<T>::with
  37: std::thread::local::LocalKey<T>::with
  38: tokio::runtime::threadpool::builder::Builder::build::{{closure}}
  39: std::thread::local::LocalKey<T>::with
  40: std::thread::local::LocalKey<T>::with
  41: std::sys_common::backtrace::__rust_begin_short_backtrace
  42: std::panicking::try::do_call
  43: __rust_maybe_catch_panic
  44: core::ops::function::FnOnce::call_once{{vtable.shim}}
  45: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
  46: std::sys::unix::thread::Thread::new::thread_start
  47: _pthread_start
)

stack backtrace:
   0: backtrace::backtrace::trace
   1: backtrace::capture::Backtrace::new_unresolved
   2: failure::backtrace::internal::InternalBacktrace::new
   3: <failure::backtrace::Backtrace as core::default::Default>::default
   4: <failure::error::error_impl::ErrorImpl as core::convert::From<F>>::from
   5: sql_migration_connector::sql_database_step_applier::SqlDatabaseStepApplier::apply_next_step
   6: <sql_migration_connector::sql_database_step_applier::SqlDatabaseStepApplier as migration_connector::database_migration_step_applier::DatabaseMigrationStepApplier<sql_migration_connector::sql_migration::SqlMigration>>::unapply_step
   7: <migration_connector::migration_applier::MigrationApplierImpl<T> as migration_connector::migration_applier::MigrationApplier<T>>::unapply
   8: <migration_engine::commands::unapply_migration::UnapplyMigrationCommand as migration_engine::commands::command::MigrationCommand>::execute
   9: <migration_engine::api::MigrationApi<C,D> as migration_engine::api::GenericApi>::unapply_migration
  10: migration_engine::api::rpc::RpcApi::create_sync_handler
  11: tokio_executor::enter::exit
  12: tokio_threadpool::blocking::blocking
  13: <futures::future::lazy::Lazy<F,R> as futures::future::Future>::poll
  14: futures::future::chain::Chain<A,B,C>::poll
  15: <futures::future::then::Then<A,B,F> as futures::future::Future>::poll
  16: <futures::future::lazy::Lazy<F,R> as futures::future::Future>::poll
  17: <futures::future::then::Then<A,B,F> as futures::future::Future>::poll
  18: <futures::future::map::Map<A,F> as futures::future::Future>::poll
  19: <futures::future::either::Either<A,B> as futures::future::Future>::poll
  20: <futures::future::map::Map<A,F> as futures::future::Future>::poll
  21: <futures::future::map_err::MapErr<A,F> as futures::future::Future>::poll
  22: <futures::stream::and_then::AndThen<S,F,U> as futures::stream::Stream>::poll
  23: <futures::stream::forward::Forward<T,U> as futures::future::Future>::poll
  24: <futures::future::map::Map<A,F> as futures::future::Future>::poll
  25: <futures::future::map_err::MapErr<A,F> as futures::future::Future>::poll
  26: futures::task_impl::std::set
  27: std::panicking::try::do_call
  28: __rust_maybe_catch_panic
  29: tokio_threadpool::task::Task::run
  30: tokio_threadpool::worker::Worker::run_task
  31: tokio_threadpool::worker::Worker::run
  32: std::thread::local::LocalKey<T>::with
  33: std::thread::local::LocalKey<T>::with
  34: std::thread::local::LocalKey<T>::with
  35: tokio::runtime::threadpool::builder::Builder::build::{{closure}}
  36: std::thread::local::LocalKey<T>::with
  37: std::thread::local::LocalKey<T>::with
  38: std::sys_common::backtrace::__rust_begin_short_backtrace
  39: std::panicking::try::do_call
  40: __rust_maybe_catch_panic
  41: core::ops::function::FnOnce::call_once{{vtable.shim}}
  42: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
  43: std::sys::unix::thread::Thread::new::thread_start
  44: _pthread_start
)

stack backtrace:
   0: backtrace::backtrace::trace
   1: backtrace::capture::Backtrace::new_unresolved
   2: failure::backtrace::internal::InternalBacktrace::new
   3: <failure::backtrace::Backtrace as core::default::Default>::default
   4: <failure::error::error_impl::ErrorImpl as core::convert::From<F>>::from
   5: <sql_migration_connector::sql_database_step_applier::SqlDatabaseStepApplier as migration_connector::database_migration_step_applier::DatabaseMigrationStepApplier<sql_migration_connector::sql_migration::SqlMigration>>::unapply_step
   6: <migration_connector::migration_applier::MigrationApplierImpl<T> as migration_connector::migration_applier::MigrationApplier<T>>::unapply
   7: <migration_engine::commands::unapply_migration::UnapplyMigrationCommand as migration_engine::commands::command::MigrationCommand>::execute
   8: <migration_engine::api::MigrationApi<C,D> as migration_engine::api::GenericApi>::unapply_migration
   9: migration_engine::api::rpc::RpcApi::create_sync_handler
  10: tokio_executor::enter::exit
  11: tokio_threadpool::blocking::blocking
  12: <futures::future::lazy::Lazy<F,R> as futures::future::Future>::poll
  13: futures::future::chain::Chain<A,B,C>::poll
  14: <futures::future::then::Then<A,B,F> as futures::future::Future>::poll
  15: <futures::future::lazy::Lazy<F,R> as futures::future::Future>::poll
  16: <futures::future::then::Then<A,B,F> as futures::future::Future>::poll
  17: <futures::future::map::Map<A,F> as futures::future::Future>::poll
  18: <futures::future::either::Either<A,B> as futures::future::Future>::poll
  19: <futures::future::map::Map<A,F> as futures::future::Future>::poll
  20: <futures::future::map_err::MapErr<A,F> as futures::future::Future>::poll
  21: <futures::stream::and_then::AndThen<S,F,U> as futures::stream::Stream>::poll
  22: <futures::stream::forward::Forward<T,U> as futures::future::Future>::poll
  23: <futures::future::map::Map<A,F> as futures::future::Future>::poll
  24: <futures::future::map_err::MapErr<A,F> as futures::future::Future>::poll
  25: futures::task_impl::std::set
  26: std::panicking::try::do_call
  27: __rust_maybe_catch_panic
  28: tokio_threadpool::task::Task::run
  29: tokio_threadpool::worker::Worker::run_task
  30: tokio_threadpool::worker::Worker::run
  31: std::thread::local::LocalKey<T>::with
  32: std::thread::local::LocalKey<T>::with
  33: std::thread::local::LocalKey<T>::with
  34: tokio::runtime::threadpool::builder::Builder::build::{{closure}}
  35: std::thread::local::LocalKey<T>::with
  36: std::thread::local::LocalKey<T>::with
  37: std::sys_common::backtrace::__rust_begin_short_backtrace
  38: std::panicking::try::do_call
  39: __rust_maybe_catch_panic
  40: core::ops::function::FnOnce::call_once{{vtable.shim}}
  41: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
  42: std::sys::unix::thread::Thread::new::thread_start
  43: _pthread_start
)
```

**Comment by pantharshit00** [comment] 2020-05-26 06:50
Unable to reproduce this in the latest version: 
![image](https://user-images.githubusercontent.com/22195362/82869004-33e17a80-9f4b-11ea-89ee-a053dcb16521.png)

**Comment by tomhoule** [comment] 2020-11-05 10:20
Migration rollbacks were completely revamped, and this error hasn't been seen in the wild for a long time, so I will close this issue. If you have a reproduction with a recent migrate version, please open a new issue. Thank you!

**Closed by tomhoule** 2020-11-05 10:20 UTC
Labels: bug/0-needs-info, kind/bug, status/needs-action
