### ISSUE TITLE
running migrate

### ISSUE THREAD

**Issue by hyusetiawan** [prisma/migrate#654] opened 2020-11-25 11:10 UTC
Hi Prisma Team! Prisma Migrate just crashed. 

## Versions
      
| Name        | Version            |
|-------------|--------------------|
| Platform    | darwin             | 
| Node        | v14.14.0           | 
| Prisma CLI  | 2.12.0             | 
| Binary      | cf0680a1bfe8d5e743dc659cc7f08009f9587d58| 

## Error
```
Error: Error in migration engine.
Reason: [libs/datamodel/core/src/transform/ast_to_dml/validate.rs:226:34] called `Option::unwrap()` on a `None` value

Please create an issue in the migrate repo with
your `schema.prisma` and the prisma command you tried to use 🙏:
https://github.com/prisma/migrate/issues/new

```
the version: 2.12.0

**Comment by tomhoule** [comment] 2020-12-17 13:30
Closing this as a duplicate of https://github.com/prisma/prisma/issues/4678

**Closed by tomhoule** 2020-12-17 13:30 UTC
Labels: engines/data model parser, team/migrations
