### ISSUE TITLE
Error message for wrong `url` looks bad

### ISSUE THREAD

**Issue by janpio** [prisma/migrate#496] opened 2020-07-02 16:55 UTC
```
generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "sqlite"
  url      = "./dev.db"
}

model User {
  id    String  @default(cuid()) @id
  email String  @unique
  name  String?
}

```

leads to

```
C:\Users\Jan\Documents\prisma2-e2e-tests\databases\bedrock>prisma migrate save --experimental
Error: Get config {"is_panic":false,"message":"error: Error validating datasource `db`: The URL for datasource `db` must start with the protocol `sqlite://`.\n  -->  schema.prisma:7\n   | \n 6 |   provider = \"sqlite\"\r\n 7 |   url      = \"./dev.db\"\r\n   | \n\nValidation Error Count: 1","meta":{"full_error":"error: Error validating datasource `db`: The URL for datasource `db` must start with the protocol `sqlite://`.\n  -->  schema.prisma:7\n   | \n 6 |   provider = \"sqlite\"\r\n 7 |   url      = \"./dev.db\"\r\n   | \n\nValidation Error Count: 1"},"error_code":"P1012"}
```

**Comment by albertoperdomo** [comment] 2020-08-05 09:38
Duplicate of #528.

**Closed by albertoperdomo** 2020-08-05 09:38 UTC
Labels: bug/1-repro-available, process/candidate
