### ISSUE TITLE
Getting a 'no default' on new columns in a migration

### ISSUE THREAD

**Issue by lucasjohnston** [prisma/migrate#603] opened 2020-09-30 22:12 UTC
## Bug description
Introducing a new column: `userHandle      String    @default(uuid())`, but getting told this is not possible as there is no default variable present.
```
Error: 

⚠️ We found migration(s) that cannot be executed:

  • Added the required column `userHandle` to the `User` table without a default value. There are 1 rows in this table, it is not possible to execute this migration.
```

## How to reproduce

1. Add new column with a default value
2. It apparently won't exist (i'm so tired 😩)

## Expected behavior

No error on this migration.

## Prisma information

```
model User {
  userUid        String @id @default(uuid())

  ...


  // Making handles uuids by default only for the purposes of migration
  userHandle      String    @default(uuid())
}
```

As you can see, it's recognised in the migration summary
<img width="517" alt="Screenshot 2020-09-30 at 23 09 43" src="https://user-images.githubusercontent.com/24899791/94745137-16497500-0372-11eb-8076-a83dd8481cfa.png">

But still results in an error
<img width="882" alt="Screenshot 2020-09-30 at 23 09 52" src="https://user-images.githubusercontent.com/24899791/94745194-28c3ae80-0372-11eb-988f-dcbb87718b62.png">

## Environment & setup

- OS: `macOS`
- Database: `PostgreSQL`
- Node.js version: `v12.18.1`
- Prisma version:

```
Environment variables loaded from prisma/.env
@prisma/cli          : 2.6.2
Current platform     : darwin
Query Engine         : query-engine 6a8054bb549e4cc23f157b0010cb2e95cb2637fb (at ../../../../.config/yarn/global/node_modules/@prisma/cli/query-engine-darwin)
Migration Engine     : migration-engine-cli 6a8054bb549e4cc23f157b0010cb2e95cb2637fb (at ../../../../.config/yarn/global/node_modules/@prisma/cli/migration-engine-darwin)
Introspection Engine : introspection-core 6a8054bb549e4cc23f157b0010cb2e95cb2637fb (at ../../../../.config/yarn/global/node_modules/@prisma/cli/introspection-engine-darwin)
Format Binary        : prisma-fmt 6a8054bb549e4cc23f157b0010cb2e95cb2637fb (at ../../../../.config/yarn/global/node_modules/@prisma/cli/prisma-fmt-darwin)
Studio               : 0.272.0
Preview Features     : atomicNumberOperations
```

**Comment by tomhoule** [comment] 2020-10-01 05:35
This is a known issue. `@default(uuid())` and `@default(cuid())` do not correspond to any database defaults, they are populated by the prisma client. So the message is right, but it's not explaining the situation well. Let's keep this issue open as a feature request to improve the message.

**Comment by lucasjohnston** [comment] 2020-10-01 20:46
That makes sense. As a workaround in the meantime, do you have any suggestions for how I could populate these fields with default random values that are unique? Or does any new column I add to a populated table have to be optional?

**Comment by tomhoule** [comment] 2020-10-02 06:35
With the current migrate, there isn't a way to do this (we are working very actively on expanding the possibilities for that kind of scenarios). In SQL you would have an expression as a default and that should work, like `uuid_generate_v4()`. The way to do this with migrate currently would indeed be to do the migrations in 3 steps:

- Add the field as optional in a first migration
- Populate it with appropriate values
- Make it required in a second migration

**Comment by lucasjohnston** [comment] 2020-10-02 16:24
Makes sense, thanks for the clarification.

**Comment by albertoperdomo** [comment] 2020-10-14 14:54
Closing as duplicate of https://github.com/prisma/migrate/issues/527

**Closed by albertoperdomo** 2020-10-14 14:54 UTC
Labels: process/candidate
