### ISSUE TITLE
Only Use A Subset of Tables from a Database

### ISSUE THREAD

**Issue by tnolan8** [prisma/migrate#541] opened 2020-08-06 08:28 UTC
## Problem

Our database currently has around 200+ tables but we currently only want to use maybe 7/8 of them with Prisma. Right now if I don't include a model for all tables in my `schema.prisma` and save a migration it will drop the tables I don't have a model for. This also leads to a load of unnecessary code being created when I generate the client.

## Suggested solution

I don't want to have to include a model for all tables in my `schema.prisma`. I want to be able to use only a subset of the tables within Prisma. 
## Alternatives

The only alternative I have right now is to include a model for each table in my `schema.prisma`.

**Comment by tomhoule** [comment] 2020-11-05 10:37
Closing this as a duplicate of https://github.com/prisma/migrate/issues/541 — we are centralizing work on this problem there.

**Closed by tomhoule** 2020-11-05 10:37 UTC
Labels: kind/feature

**Comment by tnolan8** [comment] 2020-11-05 11:18
Hi @tomhoule, whats the number of the Github issue tracking this issue? #541 is this issue!

**Comment by tomhoule** [comment] 2020-11-05 11:58
oops indeed, it's https://github.com/prisma/migrate/issues/613
