### ISSUE TITLE
Prisma Migration crashed

### ISSUE THREAD

**Issue by bhanukushwah** [prisma/migrate#607] opened 2020-10-04 04:55 UTC
Hi Prisma Team! Prisma Migrate just crashed. 

## Versions
      
| Name        | Version            |
|-------------|--------------------|
| Platform    | debian-openssl-1.1.x| 
| Node        | v14.3.0            | 
| Prisma CLI  | 2.8.0              | 
| Binary      | e6c9b4b2b7fa162d0d459d1863321f547498fcfe| 

## Error
```
Error: Error in migration engine.
Reason: [migration-engine/connectors/sql-migration-connector/src/sql_migration_persistence.rs:102:66] called `Result::unwrap()` on an `Err` value: ConnectorError { user_facing_error: None, kind: QueryError(Error querying the database: attempt to write a readonly database), context: SpanTrace [{ target: "migration_core::api", name: "ApplyMigration", fields: "migration_id=\"20201004045258\"", file: "migration-engine/core/src/api.rs", line: 94 }] }

Please create an issue in the migrate repo with
your `schema.prisma` and the prisma command you tried to use 🙏:
https://github.com/prisma/migrate/issues/new

```

**Comment by tomhoule** [comment] 2020-10-04 10:02
> `attempt to write a readonly database`

This seems to be the root cause of the problem. Are you on SQLite?

**Comment by tomhoule** [comment] 2020-12-17 13:29
Closing this now. If the issue was any other problem, please open a new one. Thanks!

**Closed by tomhoule** 2020-12-17 13:29 UTC
Labels: team/migrations
