### ISSUE TITLE
crashed after the first migration

### ISSUE THREAD

**Issue by tedoham** [prisma/migrate#625] opened 2020-10-29 06:23 UTC
Hi Prisma Team! Prisma Migrate just crashed. 

## Versions
      
| Name        | Version            |
|-------------|--------------------|
| Platform    | darwin             | 
| Node        | v14.14.0           | 
| Prisma CLI  | 2.10.0             | 
| Binary      | af1ae11a423edfb5d24092a85be11fa77c5e499c| 

## Error
```
Error: Error in migration engine.
Reason: [libs/sql-schema-describer/src/walkers.rs:214:27] index out of bounds: the len is 0 but the index is 0

Please create an issue in the migrate repo with
your `schema.prisma` and the prisma command you tried to use 🙏:
https://github.com/prisma/migrate/issues/new

```

**Comment by tomhoule** [comment] 2020-10-29 06:24
This is a known issue, we're working on fixing this. Thanks for reporting.

**Comment by tomhoule** [comment] 2020-10-29 06:26
Would you be able to share your schema and/or your migrations?

**Comment by tomhoule** [comment] 2020-10-30 07:15
We worked on this problem and just released a fix in 2.10.1. Can you confirm that this does not happen anymore with the new version?

**Comment by tomhoule** [comment] 2020-11-03 07:34
Other users confirmed the problem is gone for them in 2.10.1, so I'll close this as duplicate.

**Closed by tomhoule** 2020-11-03 07:34 UTC

**Comment by smakosh** [comment] 2020-11-07 22:37
I'm having the same issue @tomhoule

**Comment by tomhoule** [comment] 2020-11-08 09:23
Please open an issue with more details and we can look into it, it will be forgotten if it stays in the comments of a closed issue.

**Comment by smakosh** [comment] 2020-11-08 13:43
The issue happened because I wasn't using `npx prisma migrate...`, that worked fine.
