### ISSUE TITLE
Create new SQL Database missing first char on name

### ISSUE THREAD

**Issue by webnoob** [prisma/migrate#283] opened 2020-01-08 14:05 UTC
Version: Preview19
Platform: Windows 10

Running `primsma2 lift save` when the DB doesn't exist prompts to create the DB but the db name doesn't include the first char (only in the message), it creates the DB with the correct name. See this image for reference:
![image](https://user-images.githubusercontent.com/10404747/71984077-0b691600-3220-11ea-8f7f-1291d374154f.png)

Also, when you press YES, it hangs. I need to CTRL + C then run it again for it to work.

**Comment by divyenduz** [comment] 2020-01-09 16:32
Possibly a duplicate of https://github.com/prisma/prisma2/issues/1295

**Comment by webnoob** [comment] 2020-01-14 09:36
I don't think so. 

It creates the database, it just hangs until you CTRL + C. Then the naming is missing a char. I don't think it's the same.

**Comment by marvinroger** [comment] 2020-01-16 14:54
Can confirm this behavior, on MacOS, also using SQLite.

**Comment by divyenduz** [comment] 2020-01-20 14:22
Related issue: https://github.com/prisma/specs/issues/385

**Comment by pantharshit00** [comment] 2020-01-28 15:52
I tried this again and I can confirm this now with the following schema:
```
datasource db {
  provider = "sqlite" // other options are: "mysql" and "sqlite"
  url      = "file:dev.db"
}

generator client {
  provider = "prisma-client-js"
}

model Post {
  id          String   @id @default(cuid())
  title       String   @default("")
  tags        Tag[]
}

model Tag {
  id        String    @id @default(cuid())
  name      String    @default("") @unique
  posts     Post[]
}
```

I just ran `prisma2 migrate save --experimental` and indeed the first character from the database name was missing:
<img width="914" alt="image" src="https://user-images.githubusercontent.com/22195362/73280263-473a3e80-4214-11ea-9549-966979e50859.png">

**Comment by divyenduz** [comment] 2020-01-31 17:03
Internal note: dropping from current sprint

**Closed** 2020-07-06 13:09 UTC
Labels: bug/2-confirmed, kind/bug, team/typescript, topic: cli

**Comment by Jolg42** [comment] 2020-07-06 14:32
New prompt (without ink)

<img width="744" alt="Screen Shot 2020-07-06 at 16 31 40" src="https://user-images.githubusercontent.com/1328733/86604862-37ced680-bfa6-11ea-8a3e-be33a5744599.png">

**Comment by pantharshit00** [comment] 2020-07-07 06:46
Yeah noticed it yesterday when I was using dev version, pretty cool!
