### ISSUE TITLE
prisma migrations: after.ts or after.sh spawn error on Windows

### ISSUE THREAD

**Issue by unlight** [prisma/migrate#372] opened 2020-03-17 19:48 UTC
I'm trying to apply custom sql queries after migration. So I need create
`after.sh` or `after.ts`,
Example `after.ts`
```
#!/usr/bin/env node

console.log('ok');
```

When running migrate up, it erroing without details:
```
Error: spawn UNKNOWN
```

Same error with sh file with simple echo command.
Shell is `cmd.exe`, tried in `bash.exe` (built-in with git-for-windows) - same error.

OS: win 10 pro
node: v13.7.0
prisma: 2.0.0-alpha.902

**Comment by pantharshit00** [comment] 2020-04-21 11:48
This seems to be a windows specific issue. I can confirm this.

**Comment by Jolg42** [comment] 2020-09-02 07:51
Closing as `after.sh` & `after.ts` is not a supported feature as of today.

**Closed by Jolg42** 2020-09-02 07:51 UTC
Labels: bug/2-confirmed, kind/bug, status/needs-action, team/typescript, topic: windows

**Comment by unlight** [comment] 2020-09-02 15:35
What is the replacement?

**Comment by Jolg42** [comment] 2020-09-03 08:30
There is no replacement at the moment unfortunately, we're actively working on a better Prisma Migrate 😄 Nothing to try out yet.
