### ISSUE TITLE
Getting error in prisma migrate save --experimental command

### ISSUE THREAD

**Issue by hedasumit** [prisma/migrate#534] opened 2020-07-30 12:29 UTC
My prisma schema is :-

```
model Role {
  id   Int     @default(autoincrement()) @id
  name String
  users User[]
  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt
}

model User {
  id        Int      @default(autoincrement()) @id
  email     String   
  password  String
  name      String?
  roleId    Int?
  role      Role    @relation(fields: [roleId], references: [id])
  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt
}
```

I am getting the error :- 
`The above error occurred in the <TabIndexProvider> component:
    in TabIndexProvider
    in App
React will try to recreate this component tree from scratch using the error boundary you provided, App.
Warning: App: Error boundaries should implement getDerivedStateFromError(). In that method, return a state update to display an error message or fallback UI.`

**Comment by janpio** [comment] 2020-07-30 12:49
Can you please add your `prisma -v` output?
What database are you using?
Is there already something in your database?

**Comment by hedasumit** [comment] 2020-07-31 09:06
`$ prisma -v
Environment variables loaded from prisma/.env
@prisma/cli          : 2.2.2
Current platform     : darwin
Query Engine         : query-engine a9e8c3d97ef2a0cf59256e6b26097f2a80f0a6a4 (at node_modules/@prisma/cli/query-engine-darwin)
Migration Engine     : migration-engine-cli a9e8c3d97ef2a0cf59256e6b26097f2a80f0a6a4 (at /node_modules/@prisma/cli/migration-engine-darwin)
Introspection Engine : introspection-core a9e8c3d97ef2a0cf59256e6b26097f2a80f0a6a4 (at /node_modules/@prisma/cli/introspection-engine-darwin)
Format Binary        : prisma-fmt a9e8c3d97ef2a0cf59256e6b26097f2a80f0a6a4 (at /node_modules/@prisma/cli/prisma-fmt-darwin)
✨  Done in 3.28s.`

**Comment by janpio** [comment] 2020-07-31 09:48
I can confirm this with 2.2.2.

In 2.3.0 it should be fixed already though, so please upgrade to that version and try again. It will tell you that your schema file is invalid and what you need to fix it.

**Comment by Jolg42** [comment] 2020-08-05 13:38
Could not reproduce with 2.3.0 and up

<img width="642" alt="Screen Shot 2020-08-05 at 15 36 20" src="https://user-images.githubusercontent.com/1328733/89419439-a6cc5600-d731-11ea-95b1-08f113fffc88.png">

**Closed by Jolg42** 2020-08-05 13:38 UTC
Labels: 2.2, bug/1-repro-available, kind/bug, team/typescript, topic: cli, topic: tabindexprovider
