### ISSUE TITLE
Truncate migration README SQL statements with a semicolon

### ISSUE THREAD

**Issue by madebysid** [prisma/migrate#458] opened 2020-05-25 21:15 UTC
## Problem
In the `Database Steps` section of a migration's README.md, there's a list of SQL statements that Migrate took to reach a specific state.

## Suggested solution
If each statement were to be truncated with a semi-colon, it would make it easy to copy & paste the generated SQL directly into a SQL editor and execute them in one go.
Tiny, tiny QoL thing really.

## Alternatives
I can go over and type in the semi-colons myself too, but who wants to do that

## Additional context
This is the SQL generated for a migration I just `save`ed:
```sql
CREATE TABLE "public"."User" (
"active" boolean  NOT NULL DEFAULT true,"createdAt" timestamp(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP,"email" text  NOT NULL ,"id" text  NOT NULL ,"name" text   ,"registryAccessToken" text  NOT NULL ,"updatedAt" timestamp(3)  NOT NULL ,"updatedBy" text   ,
    PRIMARY KEY ("id"))

CREATE UNIQUE INDEX "User.email" ON "public"."User"("email")

CREATE UNIQUE INDEX "User.registryAccessToken" ON "public"."User"("registryAccessToken")

ALTER TABLE "public"."User" ADD FOREIGN KEY ("updatedBy")REFERENCES "public"."User"("id") ON DELETE SET NULL  ON UPDATE CASCADE

DROP TYPE "ScoutingFile"
```

**Comment by pantharshit00** [comment] 2020-05-26 08:29
Duplicate of #374

**Closed by pantharshit00** 2020-05-26 08:29 UTC
Labels: kind/improvement, process/candidate
