### ISSUE TITLE
`prisma migrate save` output is formatted strangely

### ISSUE THREAD

**Issue by janpio** [prisma/migrate#353] opened 2020-02-20 20:39 UTC
![image](https://user-images.githubusercontent.com/183673/74976644-6e59e980-5429-11ea-85e4-c7c2e7a80142.png)

```
C:\Users\Jan\Documents\throwaway\512  (512@1.0.0)
λ prisma2 migrate save --experimental
√ Name of migration ... init
�  migrate save --name init

New datamodel:

// This is your Prisma schema file,
// learn more about it in the docs: https://pris.ly/d/prisma-schema

datasource db {
  provider = "sqlite"
  url      = "file:dev.db"
}

generator client {
  provider = "prisma-client-js"
}

model locations {
  id        String   @id
  latitude  Float
  longitude Float
}

Prisma Migrate just created your migration 20200220213750-init in

migrations/
  └─ 20200220213750-init/
    └─ steps.json
    └─ schema.prisma
    └─ README.md

Run prisma2 migrate up --experimental to apply the migration

```

**Comment by pantharshit00** [comment] 2020-02-26 13:30
![Uploading image.png…]()


I can confirm this

**Comment by Jolg42** [comment] 2020-07-08 08:06
Closing as duplicate of https://github.com/prisma/migrate/issues/475

**Closed by Jolg42** 2020-07-08 08:06 UTC
Labels: bug/2-confirmed, kind/bug, team/typescript, topic: cli-migrate-save
