### ISSUE TITLE
preview025 causes migration error for Postgres db

### ISSUE THREAD

**Issue by heymartinadams** [prisma/migrate#383] opened 2020-03-27 15:48 UTC
## Bug description
Unable to connect to postgres db with new `preview025`. Works with `preview024`.

## How to reproduce
1. Change schema.
2. Attempt to commit the changes: `npx prisma2 migrate save --experimental`

## Prisma information 
```
$ npx prisma2 migrate save --experimental
Error: Error in migration engine: Mar 27 08:44:36.142  INFO migration_engine: Starting migration engine RPC server git_hash="8814060fa684793b73d07dbfccd4b7777b3361ae"
Mar 27 08:44:36.659  INFO quaint::single: Starting a postgresql pool with 1 connections.
Mar 27 08:44:37.069  INFO tokio_postgres::connection: NOTICE: schema "public" already exists, skipping    
error Command failed with exit code 1.
```

## Environment & setup
- macOS
- PostgreSQL
- Prisma preview025
- Node.js version: 12.6.0

**Comment by janpio** [comment] 2020-03-27 20:25
Is this reproducible with a new project created with `prisma2 init` and a trivial schema?

**Comment by heymartinadams** [comment] 2020-03-28 18:57
Hi @janpio, was unable to reproduce my error, so closing...

**Comment by janpio** [comment] 2020-03-30 01:28
We should look into this anyway for existing databaes.

**Comment by heymartinadams** [comment] 2020-03-30 05:02
Lmk what you need from me to help you figure out what happened (no issues since, fyi).

**Comment by janpio** [comment] 2020-04-09 12:43
Internal Note: This is about having a fallback error message when the engine dies and no real error message is returned.

**Comment by timsuchanek** [comment] 2020-04-16 10:04
I had a quick look into this and provided invalid Postgres credentials, but can't reproduce this. Keeping this open until we have more info.

**Comment by heymartinadams** [comment] 2020-04-16 15:39
It could very well have been due to my own not knowing what the heck I was doing, @timsuchanek — good chance that happened 😄

**Comment by janpio** [comment] 2020-05-04 17:52
Closing for now then. Feel free to reopen or comment if something like this happens again.

**Comment by timsuchanek** [comment] 2020-05-14 08:48
Seems like we forgot to close or GitHub didn't store it.

**Closed by timsuchanek** 2020-05-14 08:48 UTC
Labels: bug/0-needs-info, kind/bug, team/typescript
