### ISSUE TITLE
'prisma2 migrate up' causes error 

### ISSUE THREAD

**Issue by ifndefdeadmau5** [prisma/migrate#343] opened 2020-02-07 11:51 UTC
I'm trying to create database schema with `prisma2 migrate`
so when I running

> prisma2 migrate up --experimental

it shows an error below
```
ERROR  Oops, an unexpected error occured!
Failure during a migration command: Connector error. (error: Error querying the database: Error querying the database: Err
or querying the database: Server error: `ERROR 42S02 (1146): Table '{SchemaName}._migration' doesn't exist')
```

My prisma2 version:
"prisma2": "^2.0.0-preview020.3",

**Comment by pantharshit00** [comment] 2020-02-08 00:57
Are you on windows? If yes, this would be a duplicate of https://github.com/prisma/migrate/issues/339 which is confirmed bug.

**Comment by ifndefdeadmau5** [comment] 2020-02-08 03:55
No I'm on mac os

**Comment by pantharshit00** [comment] 2020-02-11 12:31
@ifndefdeadmau5 In that case, can you please share your schema? Also, please make sure that the database that you are using is not hosted on a windows machine with InnoDB mysql engine.

**Comment by ifndefdeadmau5** [comment] 2020-02-12 01:31
@pantharshit00 Was using local mysql instance, and what'd be the best way to share my schema?

**Comment by FinnFrotscher** [comment] 2020-02-14 10:19
Same error. checked the postgres logs:
```
postgres_1         | 2020-02-14T10:18:00.663306288Z 2020-02-14 10:18:00.662 UTC [38] ERROR:  relation "_Migration" already exists
postgres_1         | 2020-02-14T10:18:00.663384955Z 2020-02-14 10:18:00.662 UTC [38] STATEMENT:  CREATE TABLE "cofenster"."_Migration" ("revision" SERIAL PRIMARY KEY NOT NULL, "name" TEXT NOT NULL, "datamodel" TEXT NOT NULL, "status" TEXT NOT NULL, "applied" INTEGER NOT NULL, "rolled_back" INTEGER NOT NULL, "datamodel_steps" TEXT NOT NULL, "database_migration" TEXT NOT NULL, "errors" TEXT NOT NULL, "started_at" timestamp(3) NOT NULL, "finished_at" timestamp(3));
postgres_1         | 2020-02-14T10:18:26.725741729Z 2020-02-14 10:18:26.725 UTC [38] ERROR:  syntax error at or near ";" at character 35
postgres_1         | 2020-02-14T10:18:26.725808769Z 2020-02-14 10:18:26.725 UTC [38] STATEMENT:  ALTER TABLE "cofenster"."Project" ;
```
see the statement `STATEMENT:  ALTER TABLE "cofenster"."Project" ;`

**Comment by pantharshit00** [comment] 2020-02-14 12:33
@FinnFrotscher Can you please provide a reproduction of this issue? The information that you provided is not sufficient for the identification of the bug. Maybe you can open a new issue since this one is related to MySQL.

@ifndefdeadmau5 I can indeed reproduce this with a MySQL 5.5 installation:
<img width="1320" alt="image" src="https://user-images.githubusercontent.com/22195362/74532026-2c760280-4f54-11ea-8ba4-8f07a9441740.png">

Since we don't support it, I think we can close this issue. We have opened a new issue for warning users about older database versions: https://github.com/prisma/prisma2/issues/1591

**Closed by pantharshit00** 2020-02-14 12:33 UTC
Labels: bug/0-needs-info, kind/bug

**Comment by FinnFrotscher** [comment] 2020-03-11 13:08
@pantharshit00 https://github.com/prisma/migrate/issues/365
