### ISSUE TITLE
Error: undefined: Unknown error occured: Failure during a migration command: Connector error. (error: Error querying the database: Error querying the database: db error: ERROR: syntax error at or near "NOT" )

### ISSUE THREAD

**Issue by baskar007** [prisma/migrate#532] opened 2020-07-29 09:01 UTC
report id **9526**

## Bug description

cmd "`npx prisma migrate save --experimental`" not working with postgresql. following error log is displayed when running this cmd

`Error: undefined: Unknown error occured: Failure during a migration command: Connector error. (error: Error querying the database: Error querying the database: db error: ERROR: syntax error at or near "NOT" )
`
## How to reproduce

1. clone this repo https://github.com/fivethree-team/nestjs-prisma-starter
2. yarn install
3. add .env file with DATABASE_URL="postgresql://postgres:postgres@DB_IPADDRESS:5432/DB_NAME?schema=public"
4. yarn prisma migrate save --experimental

## Expected behavior

cmd should succeed when provided with correct db  and prisma model details.

## Prisma information

```prisma
datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

generator client {
  provider = "prisma-client-js"
}

model User {
  id        String   @default(cuid()) @id
  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt
  email     String   @unique
  password  String
  firstname String?
  lastname  String?
  posts     Post[]
  role      Role
}

model Post {
  id        String   @default(cuid()) @id
  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt
  published Boolean
  title     String
  content   String?
  author    User?    @relation(fields: [authorId], references: [id])
  authorId  String?
}

enum Role {
  ADMIN
  USER
}
```

## Environment & setup

- OS: Mac OS...  (PostgresSql running in vagrant box CentOS)
- Database: PostgreSQL
- Node.js version: v14.2.0
- Prisma version:
`@prisma/cli          : 2.3.0
Current platform     : darwin
Query Engine         : query-engine e11114fa1ea826f9e7b4fa1ced34e78892fe8e0e (at node_modules/@prisma/cli/query-engine-darwin)
Migration Engine     : migration-engine-cli e11114fa1ea826f9e7b4fa1ced34e78892fe8e0e (at node_modules/@prisma/cli/migration-engine-darwin)
Introspection Engine : introspection-core e11114fa1ea826f9e7b4fa1ced34e78892fe8e0e (at node_modules/@prisma/cli/introspection-engine-darwin)
Format Binary        : prisma-fmt e11114fa1ea826f9e7b4fa1ced34e78892fe8e0e (at node_modules/@prisma/cli/prisma-fmt-darwin)
✨  Done in 1.07s.`
```

```

**Comment by albertoperdomo** [comment] 2020-08-05 09:27
@tomhoule to reproduce

**Comment by tomhoule** [comment] 2020-08-18 06:28
I tried both in the migration engine test setup and with the [linked repo](https://github.com/fivethree-team/nestjs-prisma-starter), and did not manage to reproduce the crash, unfortunately.

**Comment by albertoperdomo** [comment] 2020-08-19 10:06
Repro not available

**Comment by janpio** [comment] 2020-08-19 18:13
"Repro available" means that a reproduction was given by the original reporter vs no information that would qualify the bug. If the reproduction works, we apply the `bug/2-confirmed` label. Otherwise the use can be asked again or the issue is closed as invalid.

**Comment by tomhoule** [comment] 2020-12-17 10:29
We think this issue was fixed in a past release — sorry I can't find the PR that fixed it anymore. If you experience this issue with a recent version of prisma migrate, please open a new issue. Thanks for reporting!

**Closed by tomhoule** 2020-12-17 10:29 UTC
Labels: bug/1-repro-available, kind/bug, status/needs-action, team/migrations
