### ISSUE TITLE
Migrate: Check the manual for the right syntax to use near 'CURRENT_TIMESTAMP

### ISSUE THREAD

**Issue by momakes** [prisma/migrate#438] opened 2020-05-05 08:14 UTC
```
Failure during a migration command: Connector error. (error: Error querying the
database: Error querying the database: Server error: `ERROR 42000 (1064): You ha
ve an error in your SQL syntax; check the manual that corresponds to your MySQL
server version for the right syntax to use near 'CURRENT_TIMESTAMP,
ALTER COLUMN `initiatedAt` DROP DEFAULT,
ALTER COLUMN `initia' at line 4'
   0: migration_core::api::ApplyMigration
           with migration_id="20200505120934"
```

_report id 4814_

What other info I can provide?

**Comment by radicand** [comment] 2020-05-07 19:00
There's a few issues open on this, I believe I've found the root cause as noted here: https://github.com/prisma/migrate/issues/429#issuecomment-625427792 . Not aware of a workaround until the prisma team can change the syntax.

**Comment by janpio** [comment] 2020-06-04 12:30
Closing this as a duplicate of https://github.com/prisma/migrate/issues/429

**Closed by janpio** 2020-06-04 12:30 UTC
Labels: bug/2-confirmed, kind/bug
