### ISSUE TITLE
Terminal freezes with an error when using prisma migrate up

### ISSUE THREAD

**Issue by mrniceknight** [prisma/migrate#522] opened 2020-07-21 11:29 UTC
## Bug description
An error occurs when using prisma migrate up
![image](https://user-images.githubusercontent.com/25801890/88049210-511b7980-cb87-11ea-9d33-c14307a9760a.png)

for additional info, here's my directory structure:
![image](https://user-images.githubusercontent.com/25801890/88049843-6218ba80-cb88-11ea-875d-1c80e6e1f73b.png)

## How to reproduce
1. run "prisma migrate up --experimental"
2. See error
## Expected behavior
Not produce an error 
## Prisma information
```
datasource db {
  provider = "mysql"
  url      = env("DATABASE_URL")
}

generator client {
  provider = "prisma-client-js"
}

model User {
  id       Int     @id @default(autoincrement())
  email    String
  password String
  token    String?
}
```

## Environment & setup

- OS: Windows 10 20H2
- Database: MySQL
- Node.js version: 12.16.1
- Prisma version:
```
@prisma/cli          : 2.2.2
Current platform     : windows
Query Engine         : query-engine a9e8c3d97ef2a0cf59256e6b26097f2a80f0a6a4 (at C:\Users\neil\Desktop\projects\prisma-todo\node_modules\@prisma\cli\query-engine-windows.exe)    
Migration Engine     : migration-engine-cli a9e8c3d97ef2a0cf59256e6b26097f2a80f0a6a4 (at C:\Users\neil\Desktop\projects\prisma-todo\node_modules\@prisma\cli\migration-engine-windows.exe)
Introspection Engine : introspection-core a9e8c3d97ef2a0cf59256e6b26097f2a80f0a6a4 (at C:\Users\neil\Desktop\projects\prisma-todo\node_modules\@prisma\cli\introspection-engine-windows.exe)
Format Binary        : prisma-fmt a9e8c3d97ef2a0cf59256e6b26097f2a80f0a6a4 (at C:\Users\neil\Desktop\projects\prisma-todo\node_modules\@prisma\cli\prisma-fmt-windows.exe)
```

**Comment by mrniceknight** [comment] 2020-07-21 12:02
Here's the DEBUG="*" details
```
Environment variables loaded from prisma\.env
  MigrateEngine:rpc starting migration engine with binary: C:\Users\neil\AppData\Roaming\npm\node_modules\@prisma\cli\migration-engine-windows.exe +0ms
  MigrateEngine:rpc SENDING RPC CALL {"id":1,"jsonrpc":"2.0","method":"listMigrations","params":{"projectInfo":"","sourceConfig":"// This is your Prisma schema file,\n// learn more about it in the docs: https://pris.ly/d/prisma-schema\n\ndatasource db {\n  provider = \"mysql\"\n  url      = env(\"DATABASE_URL\")\n}\n\ngenerator client {\n  provider = \"prisma-client-js\"\n}\n\nmodel User {\n  id       Int     @id @default(autoincrement())\n  email    String\n  password String\n  token    String?\n}\n"}} +6ms
  MigrateEngine:stderr Jul 21 19:57:57.046  INFO migration_engine: Starting migration engine RPC server git_hash="a9e8c3d97ef2a0cf59256e6b26097f2a80f0a6a4" +0ms
  MigrateEngine:stderr Jul 21 19:57:57.047  INFO quaint::single: Starting a mysql pool with 1 connections. +26ms
  MigrateEngine:stderr Jul 21 19:57:57.078  INFO ListMigrations: migration_core::commands::list_migrations: Returning 1 migrations (0 pending). +5ms
migrate up

Datamodel that will initialize the db:

// This is your Prisma schema file,
// learn more about it in the docs: https://pris.ly/d/prisma-schema

datasource db {
  provider = "mysql"
  url = "***"
}

generator client {
  provider = "prisma-client-js"
}

model User {
  id       Int     @id @default(autoincrement())
  email    String
  password String
  token    String?
}


Checking the datasource for potential data loss...
  MigrateEngine:rpc SENDING RPC CALL {"id":2,"jsonrpc":"2.0","method":"calculateDatabaseSteps","params":{"projectInfo":"","assumeToBeApplied":[],"stepsToApply":[{"tag":"CreateSource","source":"db"},{"tag":"CreateArgument","location":{"tag":"Source","source":"db"},"argument":"provider","value":"\"mysql\""},{"tag":"CreateArgument","location":{"tag":"Source","source":"db"},"argument":"url","value":"\"***\""},{"tag":"CreateModel","model":"User"},{"tag":"CreateField","model":"User","field":"id","type":"Int","arity":"Required"},{"tag":"CreateDirective","location":{"path":{"tag":"Field","model":"User","field":"id"},"directive":"id"}},{"tag":"CreateDirective","location":{"path":{"tag":"Field","model":"User","field":"id"},"directive":"default"}},{"tag":"CreateArgument","location":{"tag":"Directive","path":{"tag":"Field","model":"User","field":"id"},"directive":"default"},"argument":"","value":"autoincrement()"},{"tag":"CreateField","model":"User","field":"email","type":"String","arity":"Required"},{"tag":"CreateField","model":"User","field":"password","type":"String","arity":"Required"},{"tag":"CreateField","model":"User","field":"token","type":"String","arity":"Optional"}],"sourceConfig":"// This is your Prisma schema file,\n// learn 
more about it in the docs: https://pris.ly/d/prisma-schema\n\ndatasource db {\n  provider = \"mysql\"\n  url      = env(\"DATABASE_URL\")\n}\n\ngenerator client {\n  provider = \"prisma-client-js\"\n}\n\nmodel User {\n  id       Int     @id @default(autoincrement())\n  email    String\n  password String\n  token    String?\n}\n"}} +83ms


⚠️  There will be data loss:

  • You are about to drop the `_migration` table, which is not empty (1 rows).

√ Are you sure you want to apply this change? ... yes

Database Changes:

Migration            Database actions                          Status

20200721195627-init  1 DropTable, 1 CreateTable statements.

You can get the detailed db changes with prisma migrate up --experimental --verbose
Or read about them here:
      ./migrations/20200721195627-init/README.md

  MigrateEngine:rpc SENDING RPC CALL {"id":3,"jsonrpc":"2.0","method":"applyMigration","params":{"projectInfo":"","force":true,"migrationId":"20200721195627-init","steps":[{"tag":"CreateSource","source":"db"},{"tag":"CreateArgument","location":{"tag":"Source","source":"db"},"argument":"provider","value":"\"mysql\""},{"tag":"CreateArgument","location":{"tag":"Source","source":"db"},"argument":"url","value":"\"***\""},{"tag":"CreateModel","model":"User"},{"tag":"CreateField","model":"User","field":"id","type":"Int","arity":"Required"},{"tag":"CreateDirective","location":{"path":{"tag":"Field","model":"User","field":"id"},"directive":"id"}},{"tag":"CreateDirective","location":{"path":{"tag":"Field","model":"User","field":"id"},"directive":"default"}},{"tag":"CreateArgument","location":{"tag":"Directive","path":{"tag":"Field","model":"User","field":"id"},"directive":"default"},"argument":"","value":"autoincrement()"},{"tag":"CreateField","model":"User","field":"email","type":"String","arity":"Required"},{"tag":"CreateField","model":"User","field":"password","type":"String","arity":"Required"},{"tag":"CreateField","model":"User","field":"token","type":"String","arity":"Optional"}],"sourceConfig":"// This is your Prisma schema file,\n// learn more about it in the docs: https://pris.ly/d/prisma-schema\n\ndatasource db {\n  provider = \"mysql\"\n  url      = env(\"DATABASE_URL\")\n}\n\ngenerator client {\n  provider = \"prisma-client-js\"\n}\n\nmodel User {\n  id       Int     @id @default(autoincrement())\n  email    String\n  password String\n  token    String?\n}\n"}} +1s
  MigrateEngine:rpc {
  MigrateEngine:rpc   jsonrpc: '2.0',
  MigrateEngine:rpc   error: {
  MigrateEngine:rpc     code: 4466,
  MigrateEngine:rpc     message: 'An error happened. Check the data field for details.',
  MigrateEngine:rpc     data: {
  MigrateEngine:rpc       is_panic: false,
  MigrateEngine:rpc       message: "Failure during a migration command: Connector error. (error: Error querying the database: Error querying the database: Server error: `ERROR 42S02 (1146): Table 'prisma_todo._migration' doesn't exist'\n" +
  MigrateEngine:rpc         '   0: migration_core::api::ApplyMigration\n' +
  MigrateEngine:rpc         '           with migration_id="20200721195627-init"\n' +
  MigrateEngine:rpc         '             at migration-engine\\core\\src\\api.rs:77)',
  MigrateEngine:rpc       backtrace: null
  MigrateEngine:rpc     }
  MigrateEngine:rpc   },
  MigrateEngine:rpc   id: 3
  MigrateEngine:rpc } +135ms
The above error occurred in the <TabIndexProvider> component:
    in TabIndexProvider
    in App

React will try to recreate this component tree from scratch using the error boundary you provided, App.
Warning: App: Error boundaries should implement getDerivedStateFromError(). In that method, return a state update to display an error message or fallback UI.
  prisma TypeError: Cannot read property 'Symbol(keypress-decoder)' of undefined
  prisma     at Object.emitKeypressEvents (readline.js:1131:13)
  prisma     at Object.useStdin (C:\Users\neil\AppData\Roaming\npm\node_modules\@prisma\cli\build\index.js:2:2913327)
  prisma     at TabIndexProvider (C:\Users\neil\AppData\Roaming\npm\node_modules\@prisma\cli\build\index.js:2:2313126)
  prisma     at renderWithHooks (C:\Users\neil\AppData\Roaming\npm\node_modules\@prisma\cli\build\index.js:2:2706893)
  prisma     at mountIndeterminateComponent (C:\Users\neil\AppData\Roaming\npm\node_modules\@prisma\cli\build\index.js:2:2736840)
  prisma     at beginWork$1 (C:\Users\neil\AppData\Roaming\npm\node_modules\@prisma\cli\build\index.js:2:2752820)
  prisma     at Object._s (C:\Users\neil\AppData\Roaming\npm\node_modules\@prisma\cli\build\index.js:2:2767616)
  prisma     at invokeGuardedCallback (C:\Users\neil\AppData\Roaming\npm\node_modules\@prisma\cli\build\index.js:2:2770115)
  prisma     at Ou (C:\Users\neil\AppData\Roaming\npm\node_modules\@prisma\cli\build\index.js:2:2812237)
  prisma     at performUnitOfWork (C:\Users\neil\AppData\Roaming\npm\node_modules\@prisma\cli\build\index.js:2:2801113) +0ms

```

**Comment by janpio** [comment] 2020-07-22 10:47
What terminal are you using @mrniceknight?

**Comment by Slmii** [comment] 2020-07-22 19:19
Same error here when running `migrate up`

This worked for at first (was also initializing the db)
```
generator client {
provider = "prisma-client-js"
}

datasource db {
	provider = "mysql"
	url      = env("DATABASE_URL")
}

model User {
	id		      Int       @default(autoincrement()) @id
	uuid               String    @default(uuid())
	email              String    @unique
	first_name       String
	last_name       String
	password        String
	status              Boolean   @default(true)
	userGroup       UserGroup @relation(fields: [user_group_id], references: [id])
	user_group_id Int
	created_at       DateTime  @default(now())
	updated_at	DateTime  @updatedAt
}

model UserGroup {
	id		    Int       @default(autoincrement()) @id
	uuid        String    @default(uuid())
	name  		String
	description String? 
	created_at  DateTime  @default(now())
	updated_at	DateTime  @updatedAt

	users 		User[]
}
```
afterwards when adding another model and relations like below
```
model User {
    	roles 		  Role[]
}

model Role {
	id		    Int       @default(autoincrement()) @id
	uuid        String    @default(uuid())
	name  		String
	description String? 
	created_at  DateTime  @default(now())
	updated_at	DateTime  @updatedAt

	users 	 	User[]
}
```
the error occurs when running `migrate up`. I can see that the query is available in the `README.md` but its not being executed I think... The terminal I used was VSC's terminal.

**Comment by mrniceknight** [comment] 2020-07-22 20:02
I'm using git bash for windows.

**Comment by janpio** [comment] 2020-07-22 20:55
Can you try using a different one just to run this command?

**Comment by Slmii** [comment] 2020-07-26 20:49
I also have this issue, saying `Table 'x._migration' doesn't exist'\n" `. Using visual studio's terminal, git bash

**Comment by tomhoule** [comment] 2020-07-27 08:10
This is a known issue around the default settings for MySQL on windows [doing something weird](https://dev.mysql.com/doc/refman/8.0/en/identifier-case-sensitivity.html) with case conversions for identifiers, We want to find the time to investigate this soon. There is a [tracking issue](https://github.com/prisma/prisma-engines/issues/950).

We should however keep this issue open, because we have to fix the error handling. We should return a readable error here.

**Comment by Jolg42** [comment] 2020-08-05 13:48
The source of the problem is about this error `ERROR 42S02 (1146): Table 'prisma_todo._migration' doesn't exist`

Closing for now, the tracking issue about <TabIndexProvider> component is here https://github.com/prisma/migrate/issues/521

**Closed by Jolg42** 2020-08-05 13:48 UTC
Labels: bug/0-needs-info, kind/bug, team/typescript, topic: cli, topic: tabindexprovider, topic: windows
